services:
  mysql-web:
    image: mysql:8.0
    container_name: hdbhms-mysql-web
    restart: always
    ports:
      - "3308:3306"
    volumes:
      - hdbhms_mysql_web_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hdbhms_web

  redis-web:
    image: redis:7
    container_name: hdbhms-redis-web
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - hdbhms_redis_web_data:/data

volumes:
  hdbhms_mysql_web_data:
    name: hdbhms_mysql_web_data
  hdbhms_redis_web_data:
    name: hdbhms_redis_web_data
