services:
  mysql:
    image: mysql:8.0.40-debian
    container_name: "hdbhms-mysql-data"
    hostname: mysql
    restart: always
    ports:
      - '3307:3306'
    volumes:
      - "hdbhms_mysql_data:/data"
    environment:
      MYSQL_ROOT_PASSWORD: root
  redis:
    image: "redis:latest"
    container_name: "hdbhms-redis-cache"
    ports:
      - "6378:6379"
    volumes:
      - "hdbhms_redis_data:/data"
  kafka:
    image: apache/kafka:3.8.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # KRaft required settings
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      # Auto-format storage (one-time)
      KAFKA_FORMAT_STORAGE: "true"
    volumes:
      - hdbhms_kafka_data:/var/lib/kafka/data
volumes:
  hdbhms_mysql_data:
  hdbhms_redis_data:
  hdbhms_kafka_data: