package com.sep490.hdbhms.scheduling.domain.value_objects;

public enum TaskType {
    INVOICE_REMINDER,
    DEBT_WARNING,
    CONTRACT_EXPIRY,
    ROOM_STATUS_AUTOMATION,
    MAINTENANCE_FOLLOWUP,
    ROOM_HOLD_EXPIRATION,
    UTILITY_MONTHLY_RUN,
    SCHEDULED_BILLING_CHARGES,
    DEBT_OVERDUE_SCAN,
    INVOICE_OVERDUE_WARNINGS,
    NOTIFICATION_OUTBOX_DISPATCH,
    EXPIRED_ROOM_HOLD_RECONCILE,
    VISIT_REQUEST_TRASH_CLEANUP,
    ROOM_TRANSFER_TIMEOUT,
    CONTRACT_LIFECYCLE_SCAN,
    OTHER
}
