server:
  port: 8080
  forward-headers-strategy: framework
spring:
  application:
    name: hdbhms
  profiles:
    active: dev
  autoconfigure:
    exclude:
  #      - org.springframework.boot.autoconfigure.cache.JCacheCacheConfiguration
  main:
    allow-circular-references: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_MAIL_USERNAME}
    password: ${SMTP_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  cache:
    cache-names:
      - role-permissions
    caffeine:
      spec: maximumSize=500,expireAfterWrite=5m
  jackson:
    property-naming-strategy: SNAKE_CASE
app:
  auth:
    token-secret: ${SIGNER_KEY}
    token-expiration-sec: 3600 #1h
    token-refresh-sec: 2592000 #30d
  default:
    admin:
      username: ${ADMIN_USERNAME}
      email: ${ADMIN_EMAIL}
      password: ${ADMIN_PASSWORD}
  reset-password:
    reset-password-confirmation-url: localhost:300/fshs/confirm-reset
  payment:
    provider: vnpay
    payos:
      api-key: your-payos-api-key
      base-url: https://api.payos.vn
    vnpay:
      tmn-code: ${VNPAY_TMN_CODE}
      hash-secret: ${VNPAY_HASH_SECRET}
      url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  file:
    download:
      prefix: ${DOWNLOAD_PREFIX}
    temp:
      directory: ${TEMP_PATH}
    storage:
      directory: ${INTERNAL_STORAGE_PATH}
      max-concurrency: 20
      max-batch-size: 100
      retry:
        max_attempts: 3
        initial-delay: 500
        multiplier: 2
        timeout: 300
redisson:
  bloom-filter:
    redis-url: redis://${REDIS_HOST}:${REDIS_PORT}
  cache:
    duration-mins: 30