ALTER TABLE change_requests
    MODIFY COLUMN request_type ENUM (
        'METER_READING_CORRECTION',
        'INVOICE_ADJUSTMENT',
        'RENT_PRICE_ADJUSTMENT',
        'DEPOSIT_REFUND_REQUEST',
        'ROOM_TRANSFER',
        'CONTRACT_LIQUIDATION',
        'CONTRACT_RENEWAL',
        'MOVE_OUT',
        'COMPLAINT',
        'PERMISSION_ACCESS',
        'TENANT_PROFILE_ACCESS',
        'ADD_CO_OCCUPANT',
        'EXPENSE_APPROVAL'
    ) NOT NULL;
