package com.sep490.hdbhms.shared.exception;

import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.experimental.FieldDefaults;
import org.springframework.http.HttpStatus;
import org.springframework.http.HttpStatusCode;

@Getter
@AllArgsConstructor
@FieldDefaults(level = AccessLevel.PRIVATE, makeFinal = true)
public enum     ApiErrorCode {
    UNDEFINED(0, "Undefined", "Đã xảy ra lỗi không mong muốn. Vui lòng thử lại.", HttpStatus.INTERNAL_SERVER_ERROR),
    ACCOUNT_EXISTED(10102, "Account existed", "Tài khoản đã tồn tại.", HttpStatus.CONFLICT),
    INVALID_USERNAME(10103, "Invalid newUsername", "Tên đăng nhập phải có hơn 3 ký tự.", HttpStatus.BAD_REQUEST),
    INVALID_EMAIL(10103, "Invalid phone", "Số điện thoại không hợp lệ.", HttpStatus.BAD_REQUEST),
    INVALID_PASSWORD(10103, "Invalid password", "Mật khẩu phải có ít nhất 8 ký tự.", HttpStatus.BAD_REQUEST),
    INVALID_CREDENTIALS(10503, "Invalid credentials", "Số điện thoại hoặc mật khẩu không chính xác.", HttpStatus.UNAUTHORIZED),
    ROLE_NOT_FOUND(10103, "Role not found", "Không tìm thấy vai trò tài khoản.", HttpStatus.NOT_FOUND),
    ACCOUNT_NOT_FOUND(10201, "Account not found", "Không tìm thấy tài khoản.", HttpStatus.NOT_FOUND),
    NEW_PASSWORD_IS_EMPTY(10503, "New password is empty", "Mật khẩu mới không được để trống.", HttpStatus.BAD_REQUEST),
    OLD_PASSWORD(10103, "Old password", "Mật khẩu mới không được trùng với 3 mật khẩu cũ gần nhất.", HttpStatus.BAD_REQUEST),
    RESET_PASSWORD_NOT_ALLOWED_YET(10507, "Reset password not allowed yet", "Chưa thể đặt lại mật khẩu vào thời điểm này.", HttpStatus.FORBIDDEN),
    RESET_PASSWORD_TOKEN_EXPIRED(10503, "Reset password sessionId expired", "Phiên đặt lại mật khẩu đã hết hạn.", HttpStatus.BAD_REQUEST),
    RESET_PASSWORD_TOKEN_NOT_FOUND(10501, "Reset password sessionId not found", "Không tìm thấy phiên đặt lại mật khẩu.", HttpStatus.NOT_FOUND),
    RESET_PASSWORD_TOKEN_MISMATCH(10507, "Reset password sessionId mismatch", "Phiên đặt lại mật khẩu không thuộc tài khoản được yêu cầu.", HttpStatus.CONFLICT),
    OTP_CODE_EXPIRED_OR_MISMATCH(10507, "OTP code expired or mismatch", "Mã OTP đã hết hạn hoặc không khớp với phiên hiện tại.", HttpStatus.BAD_REQUEST),
    OTP_CODE_NOT_FOUND(10501, "OTP code not found", "Không tìm thấy mã OTP.", HttpStatus.NOT_FOUND),
    IS_OAUTH2_ACCOUNT(10507, "Is OAuth2 account", "Tài khoản OAuth2 không thể đổi mật khẩu hoặc xác thực số điện thoại.", HttpStatus.CONFLICT),
    REFRESH_TOKEN_EXPIRED(10507, "Refresh sessionId expired", "Phiên đăng nhập đã hết hạn.", HttpStatus.CONFLICT),
    ACCOUNT_IS_NOT_ACTIVE(10507, "Account is not active", "Tài khoản không ở trạng thái hoạt động nên không thể thực hiện thao tác thay đổi.", HttpStatus.FORBIDDEN),
    ACCOUNT_IS_NOT_VERIFIED(10507, "Account is not verified", "Tài khoản chưa được xác thực nên một số thao tác không khả dụng.", HttpStatus.FORBIDDEN),
    ACCOUNT_IS_ALREADY_VERIFIED(10507, "Account is already verified", "Tài khoản đã được xác thực, không thể xác thực lại.", HttpStatus.CONFLICT),
    SAME_USERNAME(10304, "Same newUsername", "Tên đăng nhập mới phải khác tên đăng nhập hiện tại.", HttpStatus.BAD_REQUEST),
    CHANGE_USERNAME_NOT_ALLOWED_YET(10304, "Change username not allowed yet", "Chưa thể đổi tên đăng nhập trong vòng 30 ngày kể từ lần đổi gần nhất.", HttpStatus.BAD_REQUEST),
    CHANGE_EMAIL_NOT_ALLOWED_YET(10304, "Change phone not allowed yet", "Chưa thể đổi số điện thoại trong vòng 48 giờ kể từ lần đổi gần nhất.", HttpStatus.BAD_REQUEST),
    SAME_EMAIL(10304, "Same phone", "Số điện thoại mới phải khác số điện thoại hiện tại.", HttpStatus.BAD_REQUEST),
    SAME_PASSWORD(10304, "Same password", "Mật khẩu mới phải khác mật khẩu hiện tại.", HttpStatus.BAD_REQUEST),
    SAME_ROLE(10304, "Same role", "Vai trò mới phải khác vai trò hiện tại.", HttpStatus.BAD_REQUEST),
    SAME_STATUS(10304, "Same status", "Trạng thái mới phải khác trạng thái hiện tại.", HttpStatus.BAD_REQUEST),
    INVALID_JWT_TOKEN(10507, "Invalid JWT sessionId", "Không thể xác thực phiên đăng nhập.", HttpStatus.INTERNAL_SERVER_ERROR),
    UNAUTHENTICATED(10505, "Unauthenticated", "Phiên đăng nhập đã hết hạn.", HttpStatus.UNAUTHORIZED),
    UNAUTHORIZED(10504, "Unauthorized", "Bạn không có quyền thực hiện thao tác này", HttpStatus.FORBIDDEN),
    CURRENT_EMAIL_PASSWORD_INVALID(10503, "Current email password invalid", "Mật khẩu hiện tại không đúng", HttpStatus.BAD_REQUEST),
    CURRENT_PASSWORD_INVALID(10503, "Current password invalid", "Mật khẩu hiện tại không đúng", HttpStatus.BAD_REQUEST),
    FIRST_PASSWORD_CHANGE_NOT_REQUIRED(10304, "First password change not required", "Tài khoản không yêu cầu đổi mật khẩu lần đầu", HttpStatus.BAD_REQUEST),
    FORBIDDEN_OPERATION(10504, "Forbidden operation", "Bạn không có quyền thực hiện thao tác này", HttpStatus.FORBIDDEN),
    INVALID_REQUEST(10103, "Invalid request", "Yêu cầu không hợp lệ", HttpStatus.BAD_REQUEST),
    INVALID_REQUEST_PAYLOAD(10103, "Invalid request payload", "Dữ liệu đặt cọc không đúng định dạng. Vui lòng kiểm tra lại thông tin.", HttpStatus.BAD_REQUEST),
    OPERATION_CONFLICT(10304, "Operation conflict", "Thao tác bị xung đột", HttpStatus.CONFLICT),
    RESOURCE_NOT_FOUND(10201, "Resource not found", "Không tìm thấy tài nguyên", HttpStatus.NOT_FOUND),

    // --- STANDARDIZED BUSINESS VALIDATION ---
    ACCOUNT_NOT_FOUND_BY_EMAIL(10201, "Account not found by email", "Không tìm thấy tài khoản với email đã nhập.", HttpStatus.NOT_FOUND),
    STAFF_EMAIL_ALREADY_USED(10304, "Staff email already used", "Email đã được sử dụng", HttpStatus.CONFLICT),
    INVALID_TENANT_PROFILE_ACCESS_REQUEST(10103, "Invalid tenant profile access request", "Yêu cầu cấp quyền hồ sơ khách thuê không hợp lệ.", HttpStatus.BAD_REQUEST),
    INVALID_PERMISSION_ACCESS_REQUEST(10103, "Invalid permission access request", "Yêu cầu cấp quyền không hợp lệ.", HttpStatus.BAD_REQUEST),
    PERMISSION_GRANT_NOT_FOUND(10203, "Permission grant not found", "Không tìm thấy quyền truy cập.", HttpStatus.NOT_FOUND),
    INVALID_PERMISSION_GRANT_DURATION(10103, "Invalid permission grant duration", "Thời hạn cấp quyền không hợp lệ", HttpStatus.BAD_REQUEST),
    CURRENT_CONTRACT_NOT_FOUND(40701, "Current contract not found", "Không tìm thấy hợp đồng hiện tại", HttpStatus.NOT_FOUND),
    TRANSFER_TARGET_ROOM_NOT_FOUND(40401, "Transfer target room not found", "Không tìm thấy phòng muốn chuyển đến", HttpStatus.NOT_FOUND),
    NOMINATED_PERSON_NOT_FOUND(10202, "Nominated person not found", "Không tìm thấy người được đề cử", HttpStatus.NOT_FOUND),
    TRANSFER_CONTRACT_NOT_IN_SIGNING_SET(10103, "Transfer contract not in signing set", "Hợp đồng này không thuộc bộ hợp đồng cần ký của yêu cầu chuyển phòng.", HttpStatus.BAD_REQUEST),
    SIGNED_TRANSFER_CONTRACT_FILE_REQUIRED(10103, "Signed transfer contract file required", "Vui lòng upload file hợp đồng đã ký trước khi xác nhận đã ký.", HttpStatus.BAD_REQUEST),
    SIGNED_TRANSFER_CONTRACTS_REQUIRED_FOR_COMPLETION(10103, "Signed transfer contracts required for completion", "Vui lòng upload file hợp đồng đã ký trước khi xác nhận đủ bộ.", HttpStatus.BAD_REQUEST),
    TRANSFER_CONTRACTS_MUST_BE_CONFIRMED_INDIVIDUALLY(10103, "Transfer contracts must be confirmed individually", "Vui lòng xác nhận từng hợp đồng đã ký trước khi xác nhận đủ bộ.", HttpStatus.BAD_REQUEST),
    HOLDER_REPLACEMENT_OCCUPANTS_REQUIRED(10103, "Holder replacement occupants required", "Cần xác định người rời đi và người ở lại.", HttpStatus.BAD_REQUEST),
    CURRENT_PRIMARY_TENANT_MUST_LEAVE(10103, "Current primary tenant must leave", "Người đứng tên hiện tại phải nằm trong danh sách người rời đi.", HttpStatus.BAD_REQUEST),
    REPLACEMENT_PRIMARY_TENANT_MUST_STAY(10103, "Replacement primary tenant must stay", "Người đứng tên mới phải nằm trong danh sách người ở lại.", HttpStatus.BAD_REQUEST),
    HOLDER_REPLACEMENT_OCCUPANTS_OVERLAP(10103, "Holder replacement occupants overlap", "Danh sách người rời đi và người ở lại không được trùng nhau.", HttpStatus.BAD_REQUEST),
    HOLDER_REPLACEMENT_OCCUPANTS_UNCLASSIFIED(10103, "Holder replacement occupants unclassified", "Tất cả người đang ở phải được phân loại là rời đi hoặc ở lại.", HttpStatus.BAD_REQUEST),
    REPLACEMENT_PRIMARY_TENANT_NOT_ACTIVE(10103, "Replacement primary tenant not active", "Người đứng tên mới phải là người đang ở trong hợp đồng.", HttpStatus.BAD_REQUEST),

    MD5_DIGEST_ERROR(30203, "MD5 digest error", "Đã xảy ra lỗi khi tạo mã MD5 cho tệp.", HttpStatus.INTERNAL_SERVER_ERROR),
    VISIT_001(40101, "Visit request not found", "Không tìm thấy lịch xem phòng", HttpStatus.NOT_FOUND),
    VISIT_002(40102, "Invalid room property", "Phòng không thuộc cơ sở đã chọn", HttpStatus.BAD_REQUEST),
    VISIT_003(40103, "Invalid phone", "Số điện thoại không hợp lệ", HttpStatus.BAD_REQUEST),
    VISIT_004(40104, "Invalid visit status", "Trạng thái không hợp lệ", HttpStatus.BAD_REQUEST),
    VISIT_005(40105, "Visit request access denied", "Không có quyền thao tác", HttpStatus.FORBIDDEN),
    VISIT_006(40106, "Missing required visit request field", "Thiếu thông tin bắt buộc", HttpStatus.BAD_REQUEST),
    VISIT_007(40107, "Invalid appointment time", "Ngày giờ hẹn xem phải sau thời gian hiện tại", HttpStatus.BAD_REQUEST),
    DEPOSIT_001(40201, "Invalid deposit occupancy", "Thông tin số người ở không hợp lệ", HttpStatus.BAD_REQUEST),
    HANDOVER_001(40301, "Handover already confirmed", "Biên bản bàn giao đã được xác nhận", HttpStatus.BAD_REQUEST),

    // --- PORTAL & FILE (20xxx) ---
    HOME_DATA_NOT_FOUND(20101, "Home data not found", "Không tìm thấy dữ liệu trang chủ", HttpStatus.NOT_FOUND),
    FILE_UPLOAD_FAILED(20201, "File upload failed", "Tải tệp lên thất bại", HttpStatus.INTERNAL_SERVER_ERROR),
    FILE_DOWNLOAD_FAILED(20202, "File download failed", "Tải tệp xuống thất bại", HttpStatus.INTERNAL_SERVER_ERROR),

    // --- IDENTITY & ACCESS (10xxx) ---
    USER_PROFILE_NOT_FOUND(10202, "User profile not found", "Không tìm thấy hồ sơ người dùng", HttpStatus.NOT_FOUND),
    PERMISSION_REQUEST_NOT_FOUND(10203, "Permission request not found", "Không tìm thấy yêu cầu cấp quyền", HttpStatus.NOT_FOUND),
    EMERGENCY_CONTACT_NOT_FOUND(10204, "Emergency contact not found", "Không tìm thấy liên hệ khẩn cấp", HttpStatus.NOT_FOUND),
    IDENTITY_DOCUMENT_NOT_FOUND(10205, "Identity document not found", "Không tìm thấy giấy tờ tùy thân", HttpStatus.NOT_FOUND),

    // --- OCCUPANCY: PROPERTY & ROOM (404xx) ---
    ROOM_NOT_FOUND(40401, "Room not found", "Không tìm thấy phòng", HttpStatus.NOT_FOUND),
    ROOM_ASSET_NOT_FOUND(40402, "Room asset not found", "Không tìm thấy thiết bị phòng", HttpStatus.NOT_FOUND),
    FLOOR_NOT_FOUND(40403, "Floor not found", "Không tìm thấy tầng", HttpStatus.NOT_FOUND),
    PROPERTY_NOT_FOUND(40404, "Property not found", "Không tìm thấy cơ sở", HttpStatus.NOT_FOUND),
    PROPERTY_RULE_NOT_FOUND(40405, "Property rule not found", "Không tìm thấy nội quy", HttpStatus.NOT_FOUND),
    ROOM_HOLD_NOT_FOUND(40406, "Room hold not found", "Không tìm thấy thông tin giữ phòng", HttpStatus.NOT_FOUND),
    ROOM_IMAGE_NOT_FOUND(40407, "Room image not found", "Không tìm thấy ảnh phòng", HttpStatus.NOT_FOUND),
    PROPERTY_IMAGE_NOT_FOUND(40408, "Property image not found", "Không tìm thấy ảnh cơ sở", HttpStatus.NOT_FOUND),
    ROOM_STATUS_HISTORY_NOT_FOUND(40409, "Room status history not found", "Không tìm thấy lịch sử trạng thái phòng", HttpStatus.NOT_FOUND),
    ROOM_TRANSFER_REQUEST_NOT_FOUND(40410, "Room transfer request not found", "Không tìm thấy yêu cầu chuyển phòng", HttpStatus.NOT_FOUND),

    ROOM_TRANSFER_INVALID_STATE(40415, "Room transfer invalid state", "Yêu cầu chuyển phòng đang ở trạng thái %s; cần một trong: %s.", HttpStatus.UNPROCESSABLE_ENTITY),
    ROOM_TRANSFER_HANDOVER_ASSETS_REQUIRED(40416, "Room transfer handover assets required", "Phải nhập danh sách tài sản bàn giao khi phòng cũ trả trống.", HttpStatus.BAD_REQUEST),
    ROOM_TRANSFER_HANDOVER_ELECTRICITY_REQUIRED(40417, "Room transfer handover electricity required", "Phải nhập chỉ số điện khi bàn giao phòng.", HttpStatus.BAD_REQUEST),
    ROOM_TRANSFER_HANDOVER_DATE_INVALID(40418, "Room transfer handover date invalid", "Ngày %s không hợp lệ hoặc không được nằm trong tương lai.", HttpStatus.BAD_REQUEST),
    ROOM_TRANSFER_METER_READING_INVALID(40419, "Room transfer meter reading invalid", "Chỉ số điện bàn giao không hợp lệ hoặc nhỏ hơn chỉ số trước đó.", HttpStatus.BAD_REQUEST),
    ROOM_TRANSFER_DIFFERENCE_PAYMENT_REQUIRED(40420, "Room transfer difference payment required", "Khoản chênh lệch chuyển phòng chưa được thanh toán.", HttpStatus.UNPROCESSABLE_ENTITY),
    ROOM_TRANSFER_SETTLEMENT_REQUIRED(40421, "Room transfer settlement required", "Phải chọn phương án xử lý khoản chênh lệch chuyển phòng.", HttpStatus.BAD_REQUEST),
    ROOM_TRANSFER_SETTLEMENT_INVALID(40422, "Room transfer settlement invalid", "Phương án xử lý khoản chênh lệch chuyển phòng không phù hợp.", HttpStatus.BAD_REQUEST),
    ROOM_TRANSFER_CONTRACT_STATE_INVALID(40423, "Room transfer contract state invalid", "Hợp đồng %s đang ở trạng thái %s, không thể thực hiện bước này.", HttpStatus.UNPROCESSABLE_ENTITY),
    ROOM_TRANSFER_HOLDER_NOMINATION_REQUIRED(40424, "Room transfer holder nomination required", "Phải xác định người đứng tên thay thế trước khi tiếp tục.", HttpStatus.UNPROCESSABLE_ENTITY),
    ROOM_TRANSFER_TARGET_ROOM_INVALID(40425, "Room transfer target room invalid", "Phòng đích đang ở trạng thái %s nên không thể chuyển phòng.", HttpStatus.CONFLICT),
    ROOM_TRANSFER_TARGET_CAPACITY_EXCEEDED(40426, "Room transfer target capacity exceeded", "Phòng đích không đủ sức chứa cho số người chuyển đến.", HttpStatus.CONFLICT),
    ROOM_TRANSFER_OPEN_REQUEST_EXISTS(40427, "Room transfer open request exists", "Hợp đồng này đã có một yêu cầu chuyển phòng đang được xử lý.", HttpStatus.CONFLICT),
    ROOM_TRANSFER_SOURCE_TARGET_SAME(40428, "Room transfer source and target are the same", "Phòng đích phải khác phòng hiện tại.", HttpStatus.BAD_REQUEST),
    ROOM_TRANSFER_HANDOVER_NOT_CONFIRMED(40429, "Room transfer handover not confirmed", "Biên bản bàn giao %s chưa được xác nhận hoặc chưa có chỉ số điện.", HttpStatus.UNPROCESSABLE_ENTITY),
    ROOM_TRANSFER_FINAL_INVOICE_UNPAID(40430, "Room transfer final invoice unpaid", "Hóa đơn %s chưa được thanh toán.", HttpStatus.UNPROCESSABLE_ENTITY),
    ROOM_TRANSFER_TARGET_HOLDER_APPROVAL_REQUIRED(40431, "Room transfer target holder approval required", "Chủ phòng đích chưa phê duyệt yêu cầu chuyển phòng.", HttpStatus.UNPROCESSABLE_ENTITY),
    ROOM_TRANSFER_COMPENSATION_NOT_ALLOWED(40432, "Room transfer compensation not allowed", "Chỉ được nhập bồi thường khi phòng cũ được trả trống hoàn toàn.", HttpStatus.BAD_REQUEST),
    ROOM_TRANSFER_TYPE_INVALID(40433, "Room transfer type invalid", "Loại chuyển phòng không hợp lệ cho bước hiện tại.", HttpStatus.UNPROCESSABLE_ENTITY),
    ROOM_TRANSFER_DATE_INVALID(40434, "Room transfer date invalid", "Tháng chuyển phòng không hợp lệ.", HttpStatus.BAD_REQUEST),
    ROOM_TRANSFER_SOURCE_CONTRACT_INVALID(40435, "Room transfer source contract invalid", "Hợp đồng phòng cũ không ở trạng thái đang hiệu lực hoặc người yêu cầu không phải người ở.", HttpStatus.UNPROCESSABLE_ENTITY),
    ROOM_TRANSFER_PARTICIPANT_INVALID(40436, "Room transfer participant invalid", "Người dùng hiện tại không phải người tham gia hợp lệ của yêu cầu chuyển phòng.", HttpStatus.FORBIDDEN),
    ROOM_TRANSFER_INVOICE_NOT_FOUND(40437, "Room transfer invoice not found", "Không tìm thấy hóa đơn phát sinh trong luồng chuyển phòng.", HttpStatus.NOT_FOUND),

    // --- OCCUPANCY: LEASE & CONTRACT (407xx) ---
    LIQUIDATION_DEPOSIT_FORFEITURE_CONFIRMATION_REQUIRED(70130, "Tenant deposit forfeiture confirmation required", "Vui lòng chờ khách thuê xác nhận chấp nhận khoản mất cọc trước khi thanh lý hợp đồng.", HttpStatus.CONFLICT),
    CONTRACT_NOT_FOUND(40701, "Contract not found", "Không tìm thấy hợp đồng", HttpStatus.NOT_FOUND),
    CONTRACT_EVENT_NOT_FOUND(40702, "Contract event not found", "Không tìm thấy sự kiện hợp đồng", HttpStatus.NOT_FOUND),
    CONTRACT_HANDOVER_ITEM_NOT_FOUND(40703, "Handover item not found", "Không tìm thấy thiết bị bàn giao", HttpStatus.NOT_FOUND),
    CONTRACT_HANDOVER_RECORD_NOT_FOUND(40704, "Handover record not found", "Không tìm thấy biên bản bàn giao", HttpStatus.NOT_FOUND),
    CONTRACT_LIQUIDATION_NOT_FOUND(40705, "Liquidation not found", "Không tìm thấy biên bản thanh lý", HttpStatus.NOT_FOUND),
    CONTRACT_OCCUPANT_NOT_FOUND(40706, "Occupant not found", "Không tìm thấy người ở", HttpStatus.NOT_FOUND),
    CONTRACT_TERMINATION_NOTICE_NOT_FOUND(40707, "Termination notice not found", "Không tìm thấy thông báo chấm dứt", HttpStatus.NOT_FOUND),
    TENANT_NOT_FOUND(40708, "Tenant not found", "Không tìm thấy người thuê", HttpStatus.NOT_FOUND),
    LEAD_NOT_FOUND(40709, "Lead not found", "Không tìm thấy khách hàng tiềm năng", HttpStatus.NOT_FOUND),
    RULE_VIOLATION_NOT_FOUND(40710, "Rule violation not found", "Không tìm thấy vi phạm nội quy", HttpStatus.NOT_FOUND),
    PENDING_CONTRACT_EXISTS(40711, "Pending contract exists", "Phòng %s đã có hợp đồng %s đang ở trạng thái %s.", HttpStatus.CONFLICT),

    CONTRACT_ACTIVATION_STATUS_INVALID(40713, "Contract activation status invalid", "Không thể kích hoạt hợp đồng từ trạng thái %s.", HttpStatus.BAD_REQUEST),
    CONTRACT_SIGNED_FILE_REQUIRED(40714, "Signed contract file required", "Cần có file hợp đồng đã ký trước khi kích hoạt.", HttpStatus.BAD_REQUEST),
    CONTRACT_PRIMARY_TENANT_REQUIRED(40715, "Primary tenant required", "Cần có người đứng tên chính trước khi kích hoạt hợp đồng.", HttpStatus.BAD_REQUEST),
    CONTRACT_DATES_INVALID(40716, "Contract dates invalid", "Ngày bắt đầu và ngày kết thúc hợp đồng không hợp lệ.", HttpStatus.BAD_REQUEST),
    CONTRACT_ROOM_REQUIRED(40717, "Contract room required", "Hợp đồng phải được gắn với một phòng trước khi kích hoạt.", HttpStatus.BAD_REQUEST),
    CONTRACT_ROOM_STATUS_INVALID(40718, "Contract room status invalid", "Không thể kích hoạt hợp đồng khi phòng đang ở trạng thái %s.", HttpStatus.BAD_REQUEST),
    CONTRACT_PREVIOUS_STATUS_INVALID(40719, "Previous contract status invalid", "Không thể tái ký hợp đồng cũ từ trạng thái %s.", HttpStatus.BAD_REQUEST),
    CONTRACT_ACTIVATION_READING_REQUIRED(40720, "Contract activation reading required", "Cần nhập chỉ số điện đầu kỳ trước khi kích hoạt hợp đồng.", HttpStatus.BAD_REQUEST),
    CONTRACT_ACTIVATION_READING_INVALID(40721, "Contract activation reading invalid", "Chỉ số điện đầu kỳ (%s) không được nhỏ hơn chỉ số mới nhất (%s).", HttpStatus.BAD_REQUEST),
    CONTRACT_TRANSFER_WORKFLOW_CONFLICT(40722, "Contract transfer workflow conflict", "Hợp đồng đang thuộc một luồng chuyển phòng chưa hoàn tất.", HttpStatus.CONFLICT),
    CONTRACT_HANDOVER_TYPE_INVALID(40723, "Contract handover type invalid", "Loại bàn giao không phù hợp với endpoint này.", HttpStatus.BAD_REQUEST),
    CONTRACT_HANDOVER_ELECTRICITY_REQUIRED(40724, "Contract handover electricity required", "Phải nhập chỉ số điện khi bàn giao hợp đồng.", HttpStatus.BAD_REQUEST),

    // --- OCCUPANCY: DEPOSIT (402xx) ---
    DEPOSIT_AGREEMENT_NOT_FOUND(40201, "Deposit agreement not found", "Không tìm thấy thỏa thuận cọc", HttpStatus.NOT_FOUND),
    DEPOSIT_FORM_NOT_FOUND(40202, "Deposit form not found", "Không tìm thấy biểu mẫu cọc", HttpStatus.NOT_FOUND),
    DEPOSIT_EXTENSION_EVENT_NOT_FOUND(40203, "Deposit extension not found", "Không tìm thấy gia hạn cọc", HttpStatus.NOT_FOUND),
    DEPOSIT_AGREEMENT_CONTRACT_NOT_FOUND(40204, "Deposit agreement contract not found", "Không tìm thấy hợp đồng đặt cọc.", HttpStatus.NOT_FOUND),
    DEPOSIT_FORM_FOR_UPDATE_NOT_FOUND(40205, "Deposit form for update not found", "Không tìm thấy form đặt cọc để cập nhật thông tin khách.", HttpStatus.BAD_REQUEST),
    DEPOSIT_BATCH_NOT_FOUND(40206, "Deposit batch not found", "Không tìm thấy batch đặt cọc.", HttpStatus.NOT_FOUND),
    DEPOSIT_ALREADY_PAID(40207, "Deposit already paid", "Phòng đã được đặt cọc thành công, không thể hủy giữ chỗ.", HttpStatus.CONFLICT),
    DEPOSIT_BATCH_ALREADY_PAID(40208, "Deposit batch already paid", "Batch đã thanh toán thành công, không thể hủy giữ chỗ.", HttpStatus.CONFLICT),
    DEPOSIT_STATUS_INVALID(40209, "Invalid deposit status", "Trạng thái cọc không hợp lệ. Mất cọc phải được xử lý qua hành động có kiểm tra quá hạn.", HttpStatus.BAD_REQUEST),
    DEPOSIT_ADDRESS_REQUIRED(40210, "Deposit address required", "Địa chỉ không được để trống.", HttpStatus.BAD_REQUEST),
    DEPOSIT_PHONE_INVALID(40211, "Invalid deposit phone", "Số điện thoại phải gồm 10 chữ số và bắt đầu bằng 0", HttpStatus.BAD_REQUEST),
    DEPOSIT_LEASE_SIGN_DATE_PAST(40212, "Deposit lease sign date in past", "Ngày ký hợp đồng dự kiến không được là ngày quá khứ.", HttpStatus.BAD_REQUEST),
    DEPOSIT_MOVE_IN_DATE_PAST(40213, "Deposit move-in date in past", "Ngày vào ở dự kiến không được là ngày quá khứ.", HttpStatus.BAD_REQUEST),
    DEPOSIT_MOVE_IN_BEFORE_SIGN_DATE(40214, "Deposit move-in before sign date", "Ngày vào ở dự kiến không được trước ngày ký hợp đồng dự kiến.", HttpStatus.BAD_REQUEST),
    DEPOSIT_PAID_DATES_IMMUTABLE(40215, "Paid deposit dates immutable", "Ngày hẹn của cọc đã thanh toán chỉ được thay đổi qua hành động gia hạn.", HttpStatus.BAD_REQUEST),
    DEPOSIT_MANAGEMENT_UPDATE_NOT_ALLOWED(40216, "Deposit management update not allowed", "Chỉ được cập nhật thông tin khi cọc đang chờ thanh toán, đã đặt cọc, đang giữ cọc hoặc chờ ký hợp đồng.", HttpStatus.BAD_REQUEST),
    DEPOSIT_LIFECYCLE_TERMINAL(40217, "Deposit lifecycle terminal", "Không thể thay đổi khoản cọc đã kết thúc xử lý.", HttpStatus.BAD_REQUEST),
    DEPOSIT_CONTACT_NOT_ALLOWED(40218, "Deposit contact not allowed", "Chỉ ghi nhận liên hệ cho khoản cọc đang giữ chỗ.", HttpStatus.BAD_REQUEST),
    DEPOSIT_CONTACT_DATE_NOT_REACHED(40219, "Deposit contact date not reached", "Chỉ liên hệ xử lý từ ngày khách dự kiến vào ở.", HttpStatus.BAD_REQUEST),
    DEPOSIT_FORFEITURE_NOT_ELIGIBLE(40220, "Deposit forfeiture not eligible", "Chỉ được xử lý mất cọc sau 14 ngày quá hạn và lần liên hệ gần nhất ghi nhận không liên lạc được.", HttpStatus.BAD_REQUEST),
    DEPOSIT_EXTENSION_INVALID(40221, "Invalid deposit extension", "Thông tin gia hạn phiếu cọc không hợp lệ.", HttpStatus.BAD_REQUEST),
    DEPOSIT_ROOM_LIST_EMPTY(40222, "Deposit room list empty", "Phải có ít nhất 1 phòng để đặt cọc.", HttpStatus.BAD_REQUEST),
    DEPOSIT_ROOM_LIST_DUPLICATED(40223, "Deposit room list duplicated", "Danh sách phòng có roomId trùng lặp.", HttpStatus.BAD_REQUEST),
    DEPOSIT_ROOMS_DIFFERENT_PROPERTY(40224, "Deposit rooms belong to different properties", "Các phòng trong batch phải cùng một cơ sở.", HttpStatus.BAD_REQUEST),
    DEPOSIT_OCCUPANT_LIMIT_EXCEEDED(40225, "Deposit occupant limit exceeded", "Số người ở không hợp lệ.", HttpStatus.BAD_REQUEST),
    DEPOSIT_EXPECTED_DATE_IN_PAST(40226, "Deposit expected date in past", "Ngày dự kiến không được trước ngày hiện tại.", HttpStatus.BAD_REQUEST),
    DEPOSIT_PAYMENT_CYCLE_INVALID(40227, "Invalid deposit payment cycle", "Chu kỳ thanh toán chỉ được là 1 hoặc 3 tháng.", HttpStatus.BAD_REQUEST),
    DEPOSIT_EXPECTED_MOVE_IN_BEFORE_SIGN_DATE(40228, "Expected move-in before sign date", "Ngày dự kiến vào ở không được trước ngày hẹn ký hợp đồng.", HttpStatus.UNPROCESSABLE_ENTITY),
    DEPOSIT_EXPECTED_SIGN_DATE_BEFORE_VACANT_DATE(40229, "Expected sign date before vacant date", "Ngày hẹn ký hợp đồng phải sau hoặc bằng ngày phòng dự kiến trống.", HttpStatus.UNPROCESSABLE_ENTITY),
    DEPOSIT_EXPECTED_MOVE_IN_BEFORE_VACANT_DATE(40230, "Expected move-in before vacant date", "Ngày dự kiến vào ở phải sau hoặc bằng ngày phòng dự kiến trống.", HttpStatus.UNPROCESSABLE_ENTITY),
    DEPOSIT_EXPECTED_MOVE_IN_REQUIRED(40231, "Expected move-in date required", "Cần có ngày dự kiến vào ở.", HttpStatus.UNPROCESSABLE_ENTITY),
    DEPOSIT_EXPECTED_SIGN_DATE_REQUIRED(40232, "Expected sign date required", "Cần có ngày dự kiến ký hợp đồng.", HttpStatus.UNPROCESSABLE_ENTITY),
    DEPOSIT_EXPECTED_VACANT_DATE_MISSING(40233, "Expected vacant date missing", "Phòng sắp trống chưa có ngày dự kiến bàn giao.", HttpStatus.UNPROCESSABLE_ENTITY),
    DEPOSIT_EXPECTED_MOVE_IN_TOO_FAR(40234, "Expected move-in date too far", "Ngày dự kiến vào ở chỉ được tối đa 14 ngày kể từ hôm nay.", HttpStatus.UNPROCESSABLE_ENTITY),
    DEPOSIT_EXPECTED_SIGN_DATE_TOO_FAR(40235, "Expected sign date too far", "Ngày hẹn ký hợp đồng chỉ được tối đa 14 ngày kể từ hôm nay.", HttpStatus.UNPROCESSABLE_ENTITY),
    DEPOSIT_EXPECTED_MOVE_IN_TOO_FAR_AFTER_VACANT(40236, "Expected move-in date too far after vacant date", "Ngày dự kiến vào ở chỉ được tối đa 14 ngày kể từ ngày khách cũ trả phòng.", HttpStatus.UNPROCESSABLE_ENTITY),
    DEPOSIT_EXPECTED_SIGN_DATE_TOO_FAR_AFTER_VACANT(40237, "Expected sign date too far after vacant date", "Ngày hẹn ký hợp đồng chỉ được tối đa 14 ngày kể từ ngày khách cũ trả phòng.", HttpStatus.UNPROCESSABLE_ENTITY),
    DEPOSIT_FILE_UPLOAD_REQUIRED(40238, "Deposit file upload required", "Thiếu file CCCD hoặc ảnh chân dung.", HttpStatus.BAD_REQUEST),
    DEPOSIT_FILE_UPLOAD_FAILED(40239, "Deposit file upload failed", "Không thể upload file định danh.", HttpStatus.BAD_REQUEST),
    DEPOSIT_PAYMENT_INIT_FAILED(40240, "Deposit payment initialization failed", "Không thể khởi tạo thanh toán. Vui lòng thử lại.", HttpStatus.BAD_GATEWAY),
    BATCH_ROOM_UNAVAILABLE(40241, "Batch room unavailable", "Một số phòng đã có người đặt cọc hoặc đang được xử lý.", HttpStatus.CONFLICT),

    // --- OCCUPANCY: UTILITY & METER (409xx) ---
    METER_NOT_FOUND(40901, "Meter not found", "Không tìm thấy đồng hồ", HttpStatus.NOT_FOUND),
    METER_READING_NOT_FOUND(40902, "Meter reading not found", "Không tìm thấy chỉ số đồng hồ", HttpStatus.NOT_FOUND),
    METER_READING_BATCH_NOT_FOUND(40903, "Meter reading batch not found", "Không tìm thấy đợt chốt điện nước", HttpStatus.NOT_FOUND),
    METER_READING_IMPORT_ROW_NOT_FOUND(40904, "Meter reading import row not found", "Không tìm thấy dòng import", HttpStatus.NOT_FOUND),
    METER_READING_ANOMALY_NOT_FOUND(40905, "Meter reading anomaly not found", "Không tìm thấy bất thường chỉ số", HttpStatus.NOT_FOUND),
    UTILITY_TARIFF_NOT_FOUND(40906, "Utility tariff not found", "Không tìm thấy bảng giá điện nước", HttpStatus.NOT_FOUND),
    INVALID_METER_READING_VALUE(40907, "Invalid meter reading value", "Chỉ số mới không được nhỏ hơn chỉ số cũ", HttpStatus.BAD_REQUEST),
    METER_READING_BATCH_CANCELLED(40908, "Meter reading batch cancelled", "Đợt chốt điện nước đã bị hủy", HttpStatus.BAD_REQUEST),
    METER_READING_ROOM_NOT_ELIGIBLE(40909, "Meter reading room not eligible", "Phòng không có hợp đồng thuê phát sinh trong kỳ", HttpStatus.BAD_REQUEST),
    METER_READING_NO_ELIGIBLE_ROOMS(40910, "No rooms require meter reading", "Không có phòng cần chốt điện nước trong kỳ này", HttpStatus.BAD_REQUEST),
    METER_READING_BATCH_CONFIRMED(40911, "Meter reading batch confirmed", "Kỳ ghi chỉ số đã chốt, không thể chỉnh sửa", HttpStatus.BAD_REQUEST),
    METER_READING_INVOICES_ISSUED(40927, "Meter reading invoices issued", "Hóa đơn của kỳ này đã phát hành, không thể chỉnh sửa chỉ số điện.", HttpStatus.BAD_REQUEST),
    METER_READING_EXCEL_FILE_REQUIRED(40912, "Meter reading Excel file required", "Vui lòng chọn file Excel cần nhập chỉ số điện.", HttpStatus.BAD_REQUEST),
    METER_READING_EXCEL_XLSX_REQUIRED(40913, "Meter reading Excel xlsx required", "File nhập chỉ số điện phải có định dạng .xlsx.", HttpStatus.BAD_REQUEST),
    METER_READING_EXCEL_WORKBOOK_EMPTY(40914, "Meter reading Excel workbook empty", "File Excel không có trang tính để nhập chỉ số điện.", HttpStatus.BAD_REQUEST),
    METER_READING_EXCEL_ROOM_COLUMN_MISSING(40915, "Meter reading Excel room column missing", "Không tìm thấy cột mã phòng trong file Excel.", HttpStatus.BAD_REQUEST),
    METER_READING_EXCEL_VALUE_COLUMN_MISSING(40916, "Meter reading Excel value column missing", "Không tìm thấy cột chỉ số điện mới trong file Excel.", HttpStatus.BAD_REQUEST),
    METER_READING_EXCEL_REQUIRED_COLUMNS_MISSING(40917, "Meter reading Excel required columns missing", "File Excel phải có cột mã phòng và cột chỉ số điện mới.", HttpStatus.BAD_REQUEST),
    METER_READING_EXCEL_NO_DATA(40918, "Meter reading Excel no data", "File Excel không có dòng dữ liệu chỉ số điện.", HttpStatus.BAD_REQUEST),
    METER_READING_EXCEL_ROOM_REQUIRED(40919, "Meter reading Excel room required", "Dòng Excel %s đang thiếu mã phòng.", HttpStatus.BAD_REQUEST),
    METER_READING_EXCEL_VALUE_REQUIRED(40920, "Meter reading Excel value required", "Dòng Excel %s của phòng %s đang thiếu chỉ số điện mới.", HttpStatus.BAD_REQUEST),
    METER_READING_EXCEL_VALUE_INVALID(40921, "Meter reading Excel value invalid", "Dòng Excel %s của phòng %s có chỉ số điện mới không phải là số.", HttpStatus.BAD_REQUEST),
    METER_READING_EXCEL_VALUE_NEGATIVE(40922, "Meter reading Excel value negative", "Dòng Excel %s của phòng %s có chỉ số điện mới không được âm.", HttpStatus.BAD_REQUEST),
    METER_READING_EXCEL_DUPLICATE_ROOM(40923, "Meter reading Excel duplicate room", "Phòng %s bị lặp tại dòng Excel %s. Mỗi phòng chỉ được xuất hiện một lần.", HttpStatus.BAD_REQUEST),
    METER_READING_EXCEL_ROOM_NOT_FOUND(40924, "Meter reading Excel room not found", "Không tìm thấy phòng %s trong hệ thống (dòng Excel %s).", HttpStatus.NOT_FOUND),
    METER_READING_EXCEL_ROOM_WRONG_PROPERTY(40925, "Meter reading Excel room wrong property", "Phòng %s không thuộc cơ sở của kỳ nhập (dòng Excel %s).", HttpStatus.BAD_REQUEST),
    METER_READING_EXCEL_ROOM_NOT_ELIGIBLE(40926, "Meter reading Excel room not eligible", "Phòng %s không có hợp đồng phát sinh trong kỳ %s (dòng Excel %s).", HttpStatus.BAD_REQUEST),

    // --- BILLING & PAYMENT (30xxx) ---
    TRANSFER_SETTLEMENT_NOT_FOUND(30101, "Transfer settlement not found", "Không tìm thấy quyết toán chuyển phòng", HttpStatus.NOT_FOUND),
    PAYMENT_INTENT_NOT_FOUND(30201, "Payment intent not found", "Không tìm thấy phiên thanh toán.", HttpStatus.NOT_FOUND),
    PAYMENT_INTENT_NOT_DEPOSIT(30202, "Payment intent is not a deposit", "Phiên thanh toán không thuộc đặt cọc phòng.", HttpStatus.BAD_REQUEST),
    EXTERNAL_SERVICE_ERROR(50201, "External service error", "Không thể xử lý yêu cầu với dịch vụ bên ngoài.", HttpStatus.BAD_GATEWAY),
    EXTERNAL_SERVICE_UNAVAILABLE(50301, "External service unavailable", "Dịch vụ bên ngoài hiện không khả dụng.", HttpStatus.SERVICE_UNAVAILABLE),

    // --- ROOM BOOKING & CONTRACT STATE ---
    ROOM_DEPOSIT_HOLD_ACTIVE(40411, "Room deposit hold active", "Phòng đang có người đặt cọc. Vui lòng chờ trong giây lát.", HttpStatus.CONFLICT),
    ROOM_DEPOSIT_LOCKED(40412, "Room deposit locked", "Phòng tạm khóa đặt cọc. Vui lòng thử lại sau.", HttpStatus.LOCKED),
    ROOM_DEPOSIT_UNAVAILABLE(40413, "Room deposit unavailable", "Phòng hiện không thể đặt cọc. Vui lòng chọn phòng khác.", HttpStatus.CONFLICT),
    ROOM_ALREADY_RESERVED(40414, "Room already reserved", "Phòng đã được đặt cọc. Vui lòng chọn phòng khác.", HttpStatus.CONFLICT),
    LEASE_RENEWAL_DATES_INVALID(40712, "Invalid lease renewal dates", "Ngày bắt đầu và ngày kết thúc gia hạn không hợp lệ.", HttpStatus.BAD_REQUEST),
    INVALID_REQUEST_STATE(10104, "Invalid request state", "Trạng thái yêu cầu không hợp lệ.", HttpStatus.UNPROCESSABLE_ENTITY),

    // --- NOTIFICATION (60xxx) ---
    NOTIFICATION_NOT_FOUND(60101, "Notification not found", "Không tìm thấy thông báo", HttpStatus.NOT_FOUND),
    NOTIFICATION_OUTBOX_NOT_FOUND(60102, "Notification outbox not found", "Không tìm thấy thông báo outbox", HttpStatus.NOT_FOUND),

    // --- MIGRATED RESPONSE STATUS ERRORS ---
    MIGRATED_CHI_TIEP_NHAN_PHIEU_ANG_CHO_TIEP_NHAN(70001, "MIGRATED CHI TIEP NHAN PHIEU ANG CHO TIEP NHAN", "Chỉ tiếp nhận phiếu đang chờ tiếp nhận.", HttpStatus.BAD_REQUEST),
    MIGRATED_CHI_TU_CHOI_PHIEU_ANG_CHO_TIEP_NHAN(70002, "MIGRATED CHI TU CHOI PHIEU ANG CHO TIEP NHAN", "Chỉ từ chối phiếu đang chờ tiếp nhận.", HttpStatus.BAD_REQUEST),
    MIGRATED_CHI_HOAN_TAT_KHI_PHIEU_ANG_XU_LY(70003, "MIGRATED CHI HOAN TAT KHI PHIEU ANG XU LY", "Chỉ hoàn tất khi phiếu đang xử lý.", HttpStatus.BAD_REQUEST),
    MIGRATED_CHI_XAC_NHAN_PHIEU_ANG_CHO_XAC_NHAN(70004, "MIGRATED CHI XAC NHAN PHIEU ANG CHO XAC NHAN", "Chỉ xác nhận phiếu đang chờ xác nhận.", HttpStatus.BAD_REQUEST),
    MIGRATED_CHI_BAO_CHUA_SUA_XONG_KHI_PHIEU_ANG_CHO_XAC_NHAN(70005, "MIGRATED CHI BAO CHUA SUA XONG KHI PHIEU ANG CHO XAC NHAN", "Chỉ báo chưa sửa xong khi phiếu đang chờ xác nhận.", HttpStatus.BAD_REQUEST),
    MIGRATED_CHI_ANH_GIA_PHIEU_A_HOAN_TAT(70006, "MIGRATED CHI ANH GIA PHIEU A HOAN TAT", "Chỉ đánh giá phiếu đã hoàn tất.", HttpStatus.BAD_REQUEST),
    MIGRATED_CHI_BO_SUNG_ANH_TRUOC_SUA_KHI_PHIEU_ANG_CHO_TIEP_NHAN(70007, "MIGRATED CHI BO SUNG ANH TRUOC SUA KHI PHIEU ANG CHO TIEP NHAN", "Chỉ bổ sung ảnh trước sửa khi phiếu đang chờ tiếp nhận.", HttpStatus.BAD_REQUEST),
    MIGRATED_YEU_CAU_KHONG_HOP_LE(70008, "MIGRATED YEU CAU KHONG HOP LE", "Yêu cầu không hợp lệ", HttpStatus.BAD_REQUEST),
    MIGRATED_VUI_LONG_CHON_MOT_KY_THANG_CU_THE_DE_XUAT_EXCEL(70009, "MIGRATED VUI LONG CHON MOT KY THANG CU THE DE XUAT EXCEL", "Vui lòng chọn một kỳ tháng cụ thể để xuất Excel.", HttpStatus.BAD_REQUEST),
    MIGRATED_CHUA_CO_HOA_ON_E_XUAT(70010, "MIGRATED CHUA CO HOA ON E XUAT", "Chưa có hóa đơn để xuất", HttpStatus.BAD_REQUEST),
    MIGRATED_KHONG_CO_HOA_ON_GAN_VOI_PHONG_E_XUAT(70011, "MIGRATED KHONG CO HOA ON GAN VOI PHONG E XUAT", "Không có hóa đơn gắn với phòng để xuất", HttpStatus.BAD_REQUEST),
    MIGRATED_XUAT_FILE_EXCEL_THAT_BAI(70012, "MIGRATED XUAT FILE EXCEL THAT BAI", "Xuất file Excel thất bại", HttpStatus.INTERNAL_SERVER_ERROR),
    MIGRATED_GIA_KHUYEN_MAI_PHAI_THAP_HON_GIA_NIEM_YET_CO_BAN_CUA_PHONG(70013, "MIGRATED GIA KHUYEN MAI PHAI THAP HON GIA NIEM YET CO BAN CUA PHONG", "Giá khuyến mãi phải thấp hơn giá niêm yết cơ bản của phòng.", HttpStatus.BAD_REQUEST),
    MIGRATED_KHONG_TIM_THAY_DONG_HOA_ON(70014, "MIGRATED KHONG TIM THAY DONG HOA ON", "Không tìm thấy dòng hóa đơn.", HttpStatus.NOT_FOUND),
    MIGRATED_DONG_HOA_ON_KHONG_THUOC_HOA_ON_A_CHON(70015, "MIGRATED DONG HOA ON KHONG THUOC HOA ON A CHON", "Dòng hóa đơn không thuộc hóa đơn đã chọn.", HttpStatus.BAD_REQUEST),
    MIGRATED_CHI_HO_TRO_KHIEU_NAI_HOA_ON_IEN_NUOC(70016, "MIGRATED CHI HO TRO KHIEU NAI HOA ON IEN NUOC", "Chỉ hỗ trợ khiếu nại hóa đơn điện nước.", HttpStatus.BAD_REQUEST),
    MIGRATED_CHI_CO_THE_KHIEU_NAI_HOA_ON_IEN_NUOC_CHUA_THANH_TOAN(70017, "MIGRATED CHI CO THE KHIEU NAI HOA ON IEN NUOC CHUA THANH TOAN", "Chỉ có thể khiếu nại hóa đơn điện nước chưa thanh toán.", HttpStatus.BAD_REQUEST),
    MIGRATED_CHI_CO_THE_KHIEU_NAI_DONG_IEN_HOAC_NUOC(70018, "MIGRATED CHI CO THE KHIEU NAI DONG IEN HOAC NUOC", "Chỉ có thể khiếu nại dòng điện hoặc nước.", HttpStatus.BAD_REQUEST),
    MIGRATED_DONG_HOA_ON_CHUA_LIEN_KET_CHI_SO_IEN_NUOC(70019, "MIGRATED DONG HOA ON CHUA LIEN KET CHI SO IEN NUOC", "Dòng hóa đơn chưa liên kết chỉ số điện nước.", HttpStatus.BAD_REQUEST),
    MIGRATED_VUI_LONG_NHAP_CHI_SO_BAN_CHO_LA_UNG(70020, "MIGRATED VUI LONG NHAP CHI SO BAN CHO LA UNG", "Vui lòng nhập chỉ số bạn cho là đúng.", HttpStatus.BAD_REQUEST),
    MIGRATED_CHI_SO_E_XUAT_KHONG_UOC_NHO_HON_CHI_SO_CU(70021, "MIGRATED CHI SO E XUAT KHONG UOC NHO HON CHI SO CU", "Chỉ số đề xuất không được nhỏ hơn chỉ số cũ.", HttpStatus.BAD_REQUEST),
    MIGRATED_CHI_SO_NAY_ANG_CO_KHIEU_NAI_CHO_XU_LY(70022, "MIGRATED CHI SO NAY ANG CO KHIEU NAI CHO XU LY", "Chỉ số này đang có khiếu nại chờ xử lý.", HttpStatus.CONFLICT),
    MIGRATED_KHONG_TIM_THAY_TAI_KHOAN(70023, "MIGRATED KHONG TIM THAY TAI KHOAN", "Không tìm thấy tài khoản.", HttpStatus.UNAUTHORIZED),
    MIGRATED_KHONG_TIM_THAY_TEP_MINH_CHUNG(70024, "MIGRATED KHONG TIM THAY TEP MINH CHUNG", "Không tìm thấy tệp minh chứng.", HttpStatus.NOT_FOUND),
    MIGRATED_KHONG_TIM_THAY_HOA_ON(70025, "MIGRATED KHONG TIM THAY HOA ON", "Không tìm thấy hóa đơn.", HttpStatus.NOT_FOUND),
    MIGRATED_KHONG_THE_LUU_DU_LIEU_KHIEU_NAI(70026, "MIGRATED KHONG THE LUU DU LIEU KHIEU NAI", "Không thể lưu dữ liệu khiếu nại.", HttpStatus.INTERNAL_SERVER_ERROR),
    MIGRATED_BAN_KHONG_CO_QUYEN_XEM_PHIEU_SU_CO_CUA_CO_SO_NAY(70027, "MIGRATED BAN KHONG CO QUYEN XEM PHIEU SU CO CUA CO SO NAY", "Bạn không có quyền xem phiếu sự cố của cơ sở này.", HttpStatus.FORBIDDEN),
    MIGRATED_CHI_KHACH_THUE_MOI_UOC_SU_DUNG_CHUC_NANG_NAY(70028, "MIGRATED CHI KHACH THUE MOI UOC SU DUNG CHUC NANG NAY", "Chỉ khách thuê mới được sử dụng chức năng này.", HttpStatus.FORBIDDEN),
    MIGRATED_BAN_KHONG_CO_QUYEN_XEM_BAO_CAO_CHI_PHI_NOI_BO(70029, "MIGRATED BAN KHONG CO QUYEN XEM BAO CAO CHI PHI NOI BO", "Bạn không có quyền xem báo cáo chi phí nội bộ.", HttpStatus.FORBIDDEN),
    MIGRATED_KHONG_TIM_THAY_PHONG(70030, "MIGRATED KHONG TIM THAY PHONG", "Không tìm thấy phòng.", HttpStatus.BAD_REQUEST),
    MIGRATED_VUI_LONG_CHON_CO_SO_HOP_LE(70031, "MIGRATED VUI LONG CHON CO SO HOP LE", "Vui lòng chọn cơ sở hợp lệ.", HttpStatus.BAD_REQUEST),
    MIGRATED_CHI_UOC_UPLOAD_TOI_A_3_ANH_HIEN_TRANG(70032, "MIGRATED CHI UOC UPLOAD TOI A 3 ANH HIEN TRANG", "Chỉ được upload tối đa 3 ảnh hiện trạng.", HttpStatus.BAD_REQUEST),
    MIGRATED_VUI_LONG_NHAP_LY_DO_TU_CHOI(70033, "MIGRATED VUI LONG NHAP LY DO TU CHOI", "Vui lòng nhập lý do từ chối.", HttpStatus.BAD_REQUEST),
    MIGRATED_CHI_CHU_TRO_UOC_SUA_CHI_PHI_CUA_TICKET_A_HOAN_TAT(70034, "MIGRATED CHI CHU TRO UOC SUA CHI PHI CUA TICKET A HOAN TAT", "Chỉ chủ trọ được sửa chi phí của ticket đã hoàn tất.", HttpStatus.FORBIDDEN),
    MIGRATED_KHONG_THE_CAP_NHAT_THONG_TIN_XU_LY_O_TRANG_THAI_NAY(70035, "MIGRATED KHONG THE CAP NHAT THONG TIN XU LY O TRANG THAI NAY", "Không thể cập nhật thông tin xử lý ở trạng thái này.", HttpStatus.BAD_REQUEST),
    MIGRATED_CHI_PHI_THUC_TE_KHONG_UOC_AM(70036, "MIGRATED CHI PHI THUC TE KHONG UOC AM", "Chi phí thực tế không được âm", HttpStatus.BAD_REQUEST),
    MIGRATED_ANH_GIA_PHAI_TU_1_EN_5_SAO(70037, "MIGRATED ANH GIA PHAI TU 1 EN 5 SAO", "Đánh giá phải từ 1 đến 5 sao.", HttpStatus.BAD_REQUEST),
    MIGRATED_BAN_A_ANH_GIA_PHIEU_NAY(70038, "MIGRATED BAN A ANH GIA PHIEU NAY", "Bạn đã đánh giá phiếu này.", HttpStatus.BAD_REQUEST),
    MIGRATED_VUI_LONG_CHON_ANH_CAN_UPLOAD(70039, "MIGRATED VUI LONG CHON ANH CAN UPLOAD", "Vui lòng chọn ảnh cần upload.", HttpStatus.BAD_REQUEST),
    MIGRATED_KHACH_THUE_CHI_UOC_UPLOAD_ANH_TRUOC_SUA(70040, "MIGRATED KHACH THUE CHI UOC UPLOAD ANH TRUOC SUA", "Khách thuê chỉ được upload ảnh trước sửa.", HttpStatus.FORBIDDEN),
    MIGRATED_BAN_KHONG_CO_QUYEN_XEM_TICKET_CUA_PHONG_NAY(70041, "MIGRATED BAN KHONG CO QUYEN XEM TICKET CUA PHONG NAY", "Bạn không có quyền xem ticket của phòng này.", HttpStatus.FORBIDDEN),
    MIGRATED_KHONG_XAC_INH_UOC_PHONG_ANG_THUE_E_TAO_PHIEU_SU_CO(70042, "MIGRATED KHONG XAC INH UOC PHONG ANG THUE E TAO PHIEU SU CO", "Không xác định được phòng đang thuê để tạo phiếu sự cố.", HttpStatus.BAD_REQUEST),
    MIGRATED_KHACH_THUE_CHI_UOC_TAO_PHIEU_SU_CO_PHONG_ANG_THUE(70043, "MIGRATED KHACH THUE CHI UOC TAO PHIEU SU CO PHONG ANG THUE", "Khách thuê chỉ được tạo phiếu sự cố phòng đang thuê.", HttpStatus.FORBIDDEN),
    MIGRATED_BAN_KHONG_CO_QUYEN_TAO_PHIEU_SU_CO_CHO_PHONG_NAY(70044, "MIGRATED BAN KHONG CO QUYEN TAO PHIEU SU CO CHO PHONG NAY", "Bạn không có quyền tạo phiếu sự cố cho phòng này.", HttpStatus.FORBIDDEN),
    MIGRATED_CHI_UOC_UPLOAD_TOI_A_3_ANH_TRUOC_SUA(70045, "MIGRATED CHI UOC UPLOAD TOI A 3 ANH TRUOC SUA", "Chỉ được upload tối đa 3 ảnh trước sửa.", HttpStatus.BAD_REQUEST),
    MIGRATED_VUI_LONG_CHON_CO_SO_PROPERTY_CHO_SU_CO_KHU_VUC_CHUNG(70046, "MIGRATED VUI LONG CHON CO SO PROPERTY CHO SU CO KHU VUC CHUNG", "Vui lòng chọn cơ sở/property cho sự cố khu vực chung.", HttpStatus.BAD_REQUEST),
    MIGRATED_KHONG_TIM_THAY_CO_SO_PROPERTY(70047, "MIGRATED KHONG TIM THAY CO SO PROPERTY", "Không tìm thấy cơ sở/property.", HttpStatus.BAD_REQUEST),
    MIGRATED_TICKET_PHONG_CAN_CO_ROOMID(70048, "MIGRATED TICKET PHONG CAN CO ROOMID", "Ticket phòng cần có roomId.", HttpStatus.BAD_REQUEST),
    MIGRATED_KHOAN_CHI_SU_CO_DA_THANH_TOAN_KHONG_THE_DOI_SO_TIEN(70049, "MIGRATED KHOAN CHI SU CO DA THANH TOAN KHONG THE DOI SO TIEN", "Khoản chi sự cố đã thanh toán, không thể đổi số tiền.", HttpStatus.CONFLICT),
    MIGRATED_KHOAN_CHI_SU_CO_DA_THANH_TOAN_KHONG_THE_CHUYEN_NGUOI_CHIU_PHI(70050, "MIGRATED KHOAN CHI SU CO DA THANH TOAN KHONG THE CHUYEN NGUOI CHIU PHI", "Khoản chi sự cố đã thanh toán, không thể chuyển người chịu phí.", HttpStatus.CONFLICT),
    MIGRATED_KHONG_TIM_THAY_CHUNG_TU_CHI_PHI(70051, "MIGRATED KHONG TIM THAY CHUNG TU CHI PHI", "Không tìm thấy chứng từ chi phí.", HttpStatus.BAD_REQUEST),
    MIGRATED_PHIEU_CHUA_CO_HOA_ON_NHAP_E_PHAT_HANH(70052, "MIGRATED PHIEU CHUA CO HOA ON NHAP E PHAT HANH", "Phiếu chưa có hóa đơn nháp để phát hành.", HttpStatus.BAD_REQUEST),
    MIGRATED_CHI_PHI_BOI_THUONG_PHAI_LON_HON_0(70053, "MIGRATED CHI PHI BOI THUONG PHAI LON HON 0", "Chi phí bồi thường phải lớn hơn 0.", HttpStatus.BAD_REQUEST),
    MIGRATED_KHONG_TIM_THAY_PHONG_DE_LEN_LICH_THU_KHACH(70054, "MIGRATED KHONG TIM THAY PHONG DE LEN LICH THU KHACH", "Không tìm thấy phòng để lên lịch thu khách.", HttpStatus.BAD_REQUEST),
    MIGRATED_KHONG_TIM_THAY_PHONG_E_XUAT_HOA_ON(70055, "MIGRATED KHONG TIM THAY PHONG E XUAT HOA ON", "Không tìm thấy phòng để xuất hóa đơn.", HttpStatus.BAD_REQUEST),
    MIGRATED_KHONG_TIM_THAY_HOP_ONG_CUA_PHIEU_SU_CO(70056, "MIGRATED KHONG TIM THAY HOP ONG CUA PHIEU SU CO", "Không tìm thấy hợp đồng của phiếu sự cố.", HttpStatus.BAD_REQUEST),
    MIGRATED_PHIEU_KHU_VUC_CHUNG_KHONG_THE_XUAT_HOA_ON_CHO_KHACH(70057, "MIGRATED PHIEU KHU VUC CHUNG KHONG THE XUAT HOA ON CHO KHACH", "Phiếu khu vực chung không thể xuất hóa đơn cho khách.", HttpStatus.BAD_REQUEST),
    MIGRATED_PHONG_CHUA_CO_HOP_ONG_ANG_HIEU_LUC_KHONG_THE_XUAT_HOA_ON_C3FA9D(70058, "MIGRATED PHONG CHUA CO HOP ONG ANG HIEU LUC KHONG THE XUAT HOA ON C3FA9D", "Phòng chưa có hợp đồng đang hiệu lực, không thể xuất hóa đơn cho khách.", HttpStatus.BAD_REQUEST),
    MIGRATED_KHONG_TIM_THAY_PHIEU_SU_CO(70059, "MIGRATED KHONG TIM THAY PHIEU SU CO", "Không tìm thấy phiếu sự cố.", HttpStatus.NOT_FOUND),
    MIGRATED_BAN_KHONG_CO_QUYEN_XU_LY_PHIEU_SU_CO_CUA_CO_SO_NAY(70060, "MIGRATED BAN KHONG CO QUYEN XU LY PHIEU SU CO CUA CO SO NAY", "Bạn không có quyền xử lý phiếu sự cố của cơ sở này.", HttpStatus.FORBIDDEN),
    MIGRATED_BAN_KHONG_CO_QUYEN_XEM_PHIEU_SU_CO_NAY(70061, "MIGRATED BAN KHONG CO QUYEN XEM PHIEU SU CO NAY", "Bạn không có quyền xem phiếu sự cố này.", HttpStatus.FORBIDDEN),
    MIGRATED_CHI_KHACH_THUE_HOP_LE_UOC_THUC_HIEN_THAO_TAC_NAY(70062, "MIGRATED CHI KHACH THUE HOP LE UOC THUC HIEN THAO TAC NAY", "Chỉ khách thuê hợp lệ được thực hiện thao tác này.", HttpStatus.FORBIDDEN),
    MIGRATED_KHACH_THUE_KHONG_UOC_XAC_NHAN_PHIEU_KHU_VUC_CHUNG(70063, "MIGRATED KHACH THUE KHONG UOC XAC NHAN PHIEU KHU VUC CHUNG", "Khách thuê không được xác nhận phiếu khu vực chung.", HttpStatus.FORBIDDEN),
    MIGRATED_BAN_KHONG_CO_QUYEN_XU_LY_PHIEU_SU_CO(70064, "MIGRATED BAN KHONG CO QUYEN XU LY PHIEU SU CO", "Bạn không có quyền xử lý phiếu sự cố.", HttpStatus.FORBIDDEN),
    MIGRATED_PHIEN_ANG_NHAP_KHONG_HOP_LE(70065, "MIGRATED PHIEN ANG NHAP KHONG HOP LE", "Phiên đăng nhập không hợp lệ.", HttpStatus.UNAUTHORIZED),
    MIGRATED_DU_LIEU_TAO_PHIEU_KHONG_HOP_LE(70066, "MIGRATED DU LIEU TAO PHIEU KHONG HOP LE", "Dữ liệu tạo phiếu không hợp lệ.", HttpStatus.BAD_REQUEST),
    MIGRATED_MO_TA_SU_CO_PHAI_CO_TOI_THIEU_10_KY_TU(70067, "MIGRATED MO TA SU CO PHAI CO TOI THIEU 10 KY TU", "Mô tả sự cố phải có tối thiểu 10 ký tự.", HttpStatus.BAD_REQUEST),
    MIGRATED_MOT_HOAC_NHIEU_FILE_KHONG_TON_TAI(70068, "MIGRATED MOT HOAC NHIEU FILE KHONG TON TAI", "Một hoặc nhiều file không tồn tại.", HttpStatus.BAD_REQUEST),
    MIGRATED_MVP_CHI_HO_TRO_ANH_JPG_JPEG_PNG_WEBP(70069, "MIGRATED MVP CHI HO TRO ANH JPG JPEG PNG WEBP", "MVP chỉ hỗ trợ ảnh jpg, jpeg, png, webp.", HttpStatus.BAD_REQUEST),
    MIGRATED_KHONG_THE_CHUYEN_TRANG_THAI_TU_TOBUSINESSSTATUS_FROM_SAN_B457BD(70070, "MIGRATED KHONG THE CHUYEN TRANG THAI TU TOBUSINESSSTATUS FROM SAN B457BD", "Không thể chuyển trạng thái phiếu sự cố.", HttpStatus.BAD_REQUEST),
    MIGRATED_TRANG_THAI_PHIEU_SU_CO_KHONG_HOP_LE(70071, "MIGRATED TRANG THAI PHIEU SU CO KHONG HOP LE", "Trạng thái phiếu sự cố không hợp lệ.", HttpStatus.BAD_REQUEST),
    MIGRATED_PHAM_VI_SU_CO_KHONG_HOP_LE(70072, "MIGRATED PHAM VI SU CO KHONG HOP LE", "Phạm vi sự cố không hợp lệ.", HttpStatus.BAD_REQUEST),
    MIGRATED_KHONG_TIM_THAY_HOP_DONG_THUE(70073, "MIGRATED KHONG TIM THAY HOP DONG THUE", "Không tìm thấy hợp đồng thuê.", HttpStatus.NOT_FOUND),
    MIGRATED_HOP_DONG_DA_ACTIVE_KHONG_UPLOAD_THAY_FILE_TRONG_LUONG_NAY(70074, "MIGRATED HOP DONG DA ACTIVE KHONG UPLOAD THAY FILE TRONG LUONG NAY", "Hợp đồng đã ACTIVE, không thể upload thay file trong luồng này.", HttpStatus.BAD_REQUEST),
    MIGRATED_HOP_DONG_THUE_DA_CO_FILE_DA_KY_GUI_REPLACE_TRUE_NEU_MUON_5BEFFD(70075, "MIGRATED HOP DONG THUE DA CO FILE DA KY GUI REPLACE TRUE NEU MUON 5BEFFD", "Hợp đồng thuê đã có file đã ký. Gửi replace=true nếu muốn thay thế.", HttpStatus.CONFLICT),
    MIGRATED_KHONG_LUU_DUOC_FILE_HOP_DONG(70076, "MIGRATED KHONG LUU DUOC FILE HOP DONG", "Không lưu được file hợp đồng.", HttpStatus.INTERNAL_SERVER_ERROR),
    MIGRATED_KHONG_TIM_THAY_HOP_ONG_THUE(70077, "MIGRATED KHONG TIM THAY HOP ONG THUE", "Không tìm thấy hợp đồng thuê.", HttpStatus.NOT_FOUND),
    MIGRATED_HOP_DONG_DA_DUOC_THANH_LY(70078, "MIGRATED HOP DONG DA DUOC THANH LY", "Hợp đồng đã được thanh lý.", HttpStatus.BAD_REQUEST),
    MIGRATED_CHI_THANH_LY_HOP_DONG_DANG_HIEU_LUC_SAP_HET_HAN_HET_HAN__43EF2F(70079, "MIGRATED CHI THANH LY HOP DONG DANG HIEU LUC SAP HET HAN HET HAN  43EF2F", "Chỉ thanh lý hợp đồng đang hiệu lực, sắp hết hạn, hết hạn hoặc chờ thanh lý.", HttpStatus.BAD_REQUEST),
    MIGRATED_HOP_ONG_CHUA_GAN_PHONG(70080, "MIGRATED HOP ONG CHUA GAN PHONG", "Hợp đồng chưa gắn phòng.", HttpStatus.BAD_REQUEST),
    MIGRATED_VUI_LONG_LAP_HO_SO_THANH_LY_TRUOC_KHI_HOAN_TAT(70081, "MIGRATED VUI LONG LAP HO SO THANH LY TRUOC KHI HOAN TAT", "Vui lòng lập hồ sơ thanh lý trước khi hoàn tất.", HttpStatus.BAD_REQUEST),
    MIGRATED_VUI_LONG_LAP_HOP_DONG_THAY_THE_CHO_NGUOI_O_LAI_TRUOC_KHI_92A4F2(70082, "MIGRATED VUI LONG LAP HOP DONG THAY THE CHO NGUOI O LAI TRUOC KHI 92A4F2", "Vui lòng lập hợp đồng thay thế cho người ở lại trước khi hoàn tất thanh lý.", HttpStatus.CONFLICT),
    MIGRATED_HOP_ONG_A_UOC_THANH_LY(70083, "MIGRATED HOP ONG A UOC THANH LY", "Hợp đồng đã được thanh lý.", HttpStatus.BAD_REQUEST),
    MIGRATED_CHI_XU_LY_THANH_LY_CHO_HOP_ONG_ANG_HIEU_LUC_SAP_HET_HAN__99FCD7(70084, "MIGRATED CHI XU LY THANH LY CHO HOP ONG ANG HIEU LUC SAP HET HAN  99FCD7", "Chỉ xử lý thanh lý cho hợp đồng đang hiệu lực, sắp hết hạn, hết hạn hoặc chờ thanh lý.", HttpStatus.BAD_REQUEST),
    MIGRATED_HO_SO_THANH_LY_A_UOC_XAC_NHAN(70085, "MIGRATED HO SO THANH LY A UOC XAC NHAN", "Hồ sơ thanh lý đã được xác nhận.", HttpStatus.BAD_REQUEST),
    MIGRATED_HOP_ONG_PHAI_CO_NGUOI_KY_CHINH(70086, "MIGRATED HOP ONG PHAI CO NGUOI KY CHINH", "Hợp đồng phải có người ký chính.", HttpStatus.BAD_REQUEST),
    MIGRATED_NGUOI_UNG_TEN_MOI_LA_BAT_BUOC(70087, "MIGRATED NGUOI UNG TEN MOI LA BAT BUOC", "Người đứng tên mới là bắt buộc.", HttpStatus.BAD_REQUEST),
    MIGRATED_HOP_ONG_KHONG_CO_NGUOI_O_ANG_HOAT_ONG(70088, "MIGRATED HOP ONG KHONG CO NGUOI O ANG HOAT ONG", "Hợp đồng không có người ở đang hoạt động.", HttpStatus.CONFLICT),
    MIGRATED_DU_LIEU_THAY_NGUOI_UNG_TEN_LA_BAT_BUOC(70089, "MIGRATED DU LIEU THAY NGUOI UNG TEN LA BAT BUOC", "Dữ liệu thay người đứng tên là bắt buộc.", HttpStatus.BAD_REQUEST),
    MIGRATED_PHONG_A_CO_MOT_HOP_ONG_KHAC_ANG_HIEU_LUC(70090, "MIGRATED PHONG A CO MOT HOP ONG KHAC ANG HIEU LUC", "Phòng đã có một hợp đồng khác đang hiệu lực.", HttpStatus.CONFLICT),
    MIGRATED_HOP_ONG_THAY_THE_KHONG_THE_SU_DUNG(70091, "MIGRATED HOP ONG THAY THE KHONG THE SU DUNG", "Hợp đồng thay thế không thể sử dụng.", HttpStatus.CONFLICT),
    MIGRATED_HOP_ONG_THAY_THE_PHAI_GIU_NGUYEN_PHONG(70092, "MIGRATED HOP ONG THAY THE PHAI GIU NGUYEN PHONG", "Hợp đồng thay thế phải giữ nguyên phòng.", HttpStatus.CONFLICT),
    MIGRATED_NGUOI_KY_CHINH_CUA_HOP_ONG_THAY_THE_KHONG_KHOP_VOI_YEU_CAU(70093, "MIGRATED NGUOI KY CHINH CUA HOP ONG THAY THE KHONG KHOP VOI YEU CAU", "Người ký chính của hợp đồng thay thế không khớp với yêu cầu.", HttpStatus.CONFLICT),
    MIGRATED_HOP_ONG_THAY_THE_PHAI_UOC_KY_TRUOC_KHI_THANH_LY(70094, "MIGRATED HOP ONG THAY THE PHAI UOC KY TRUOC KHI THANH LY", "Hợp đồng thay thế phải được ký trước khi thanh lý.", HttpStatus.CONFLICT),
    MIGRATED_TRANG_THAI_HOP_ONG_THAY_THE_KHONG_HOP_LE_E_KICH_HOAT(70095, "MIGRATED TRANG THAI HOP ONG THAY THE KHONG HOP LE E KICH HOAT", "Trạng thái hợp đồng thay thế không hợp lệ để kích hoạt.", HttpStatus.CONFLICT),
    MIGRATED_NGUOI_O_KHONG_CON_HOAT_ONG_TRONG_HOP_ONG(70096, "MIGRATED NGUOI O KHONG CON HOAT ONG TRONG HOP ONG", "Người ở không còn hoạt động trong hợp đồng.", HttpStatus.BAD_REQUEST),
    MIGRATED_KHA_NG_TA_M_THA_Y_HA_P_A_A_NG_THUA(70097, "MIGRATED KHA NG TA M THA Y HA P A A NG THUA", "Không tìm thấy hợp đồng thuê.", HttpStatus.NOT_FOUND),
    MIGRATED_HA_P_A_A_NG_A_A_A_A_C_THANH_LA(70098, "MIGRATED HA P A A NG A A A A C THANH LA", "Hợp đồng đã được thanh lý.", HttpStatus.BAD_REQUEST),
    MIGRATED_HA_P_A_A_NG_CH_A_THA_LA_P_HA_S_THANH_LA(70099, "MIGRATED HA P A A NG CH A THA LA P HA S THANH LA", "Hợp đồng chưa thể lập hồ sơ thanh lý.", HttpStatus.BAD_REQUEST),
    MIGRATED_HA_S_THANH_LA_A_A_A_A_C_XA_C_NHA_N(70100, "MIGRATED HA S THANH LA A A A A C XA C NHA N", "Hồ sơ thanh lý đã được xác nhận.", HttpStatus.BAD_REQUEST),
    MIGRATED_KHONG_THE_CAP_NHAT_HOA_DON_THANH_LY_DA_CO_THANH_TOAN(70101, "MIGRATED KHONG THE CAP NHAT HOA DON THANH LY DA CO THANH TOAN", "Không thể cập nhật hóa đơn thanh lý đã có thanh toán.", HttpStatus.CONFLICT),
    MIGRATED_KHACH_THUE_CAN_THANH_TOAN_HET_HOA_DON_CON_NO_TRUOC_KHI_H_4B2B98(70102, "MIGRATED KHACH THUE CAN THANH TOAN HET HOA DON CON NO TRUOC KHI H 4B2B98", "Khách thuê cần thanh toán hết hóa đơn còn nợ trước khi hoàn tất thanh lý.", HttpStatus.CONFLICT),
    MIGRATED_VUI_LONG_HOAN_TAT_HOAN_COC_VA_CHO_KHACH_THUE_XAC_NHAN_A__01EA02(70103, "MIGRATED VUI LONG HOAN TAT HOAN COC VA CHO KHACH THUE XAC NHAN A  01EA02", "Vui lòng hoàn tất hoàn cọc và chờ khách thuê xác nhận đã nhận tiền trước khi thanh lý hợp đồng.", HttpStatus.CONFLICT),
    MIGRATED_VUI_LONG_HOAN_TAT_BAN_GIAO_TRA_PHONG_TRUOC_KHI_THANH_LY__A12F7C(70104, "MIGRATED VUI LONG HOAN TAT BAN GIAO TRA PHONG TRUOC KHI THANH LY  A12F7C", "Vui lòng hoàn tất bàn giao trả phòng trước khi thanh lý hợp đồng.", HttpStatus.CONFLICT),
    MIGRATED_CHI_SO_MOI_KHONG_DUOC_NHO_HON_CHI_SO_CU(70105, "MIGRATED CHI SO MOI KHONG DUOC NHO HON CHI SO CU", "Chỉ số mới không được nhỏ hơn chỉ số cũ.", HttpStatus.BAD_REQUEST),
    MIGRATED_CHI_DUOC_TAI_KY_HOP_DONG_ACTIVE_EXPIRING_SOON_HOAC_EXPIRED(70106, "MIGRATED CHI DUOC TAI KY HOP DONG ACTIVE EXPIRING SOON HOAC EXPIRED", "Chỉ được tái ký hợp đồng ACTIVE, EXPIRING_SOON hoặc EXPIRED.", HttpStatus.BAD_REQUEST),
    MIGRATED_HOP_DONG_NAY_DA_CO_HOP_DONG_TAI_KY(70107, "MIGRATED HOP DONG NAY DA CO HOP DONG TAI KY", "Hợp đồng này đã có hợp đồng tái ký.", HttpStatus.CONFLICT),
    MIGRATED_HOP_DONG_CHUA_GAN_PHONG(70108, "MIGRATED HOP DONG CHUA GAN PHONG", "Hợp đồng chưa gắn phòng.", HttpStatus.BAD_REQUEST),
    MIGRATED_PHONG_DANG_CO_HOP_DONG_HIEU_LUC_KHAC(70109, "MIGRATED PHONG DANG CO HOP DONG HIEU LUC KHAC", "Phòng đang có hợp đồng hiệu lực khác.", HttpStatus.CONFLICT),
    MIGRATED_HOP_DONG_KHONG_THE_THEM_NGUOI_O_CUNG(70110, "MIGRATED HOP DONG KHONG THE THEM NGUOI O CUNG", "Hợp đồng không thể thêm người ở cùng.", HttpStatus.BAD_REQUEST),
    MIGRATED_HO_SO_NGUOI_O_CUNG_LA_BAT_BUOC(70111, "MIGRATED HO SO NGUOI O CUNG LA BAT BUOC", "Hồ sơ người ở cùng là bắt buộc.", HttpStatus.BAD_REQUEST),
    MIGRATED_NGUOI_NAY_DA_LA_NGUOI_DUNG_TEN_HOP_DONG(70112, "MIGRATED NGUOI NAY DA LA NGUOI DUNG TEN HOP DONG", "Người này đã là người đứng tên hợp đồng.", HttpStatus.CONFLICT),
    MIGRATED_KHONG_TIM_THAY_HO_SO_NGUOI_O_CUNG(70113, "MIGRATED KHONG TIM THAY HO SO NGUOI O CUNG", "Không tìm thấy hồ sơ người ở cùng.", HttpStatus.NOT_FOUND),
    MIGRATED_PHONG_DA_DAT_SO_NGUOI_O_TOI_DA(70114, "MIGRATED PHONG DA DAT SO NGUOI O TOI DA", "Phòng đã đạt số người ở tối đa.", HttpStatus.CONFLICT),
    MIGRATED_CHI_GHI_NHAN_Y_DINH_CHO_HOP_DONG_ACTIVE_HOAC_EXPIRING_SOON(70115, "MIGRATED CHI GHI NHAN Y DINH CHO HOP DONG ACTIVE HOAC EXPIRING SOON", "Chỉ ghi nhận ý định cho hợp đồng ACTIVE hoặc EXPIRING_SOON.", HttpStatus.BAD_REQUEST),
    MIGRATED_Y_DINH_KHACH_KHONG_HOP_LE(70116, "MIGRATED Y DINH KHACH KHONG HOP LE", "Ý định khách không hợp lệ.", HttpStatus.BAD_REQUEST),
    MIGRATED_CHI_GHI_NHAN_MOVE_OUT_TRANSFER_KHI_HOP_DONG_CON_3_THANG__7864D6(70117, "MIGRATED CHI GHI NHAN MOVE OUT TRANSFER KHI HOP DONG CON 3 THANG  7864D6", "Chỉ ghi nhận MOVE_OUT/TRANSFER khi hợp đồng còn 3 tháng trở xuống.", HttpStatus.UNPROCESSABLE_ENTITY),
    MIGRATED_CAN_CO_NGAY_DU_KIEN_BAN_GIAO_PHONG(70118, "MIGRATED CAN CO NGAY DU KIEN BAN GIAO PHONG", "Cần có ngày dự kiến bàn giao phòng.", HttpStatus.UNPROCESSABLE_ENTITY),
    MIGRATED_NGAY_DU_KIEN_BAN_GIAO_KHONG_DUOC_TRUOC_HOM_NAY(70119, "MIGRATED NGAY DU KIEN BAN GIAO KHONG DUOC TRUOC HOM NAY", "Ngày dự kiến bàn giao không được trước hôm nay.", HttpStatus.UNPROCESSABLE_ENTITY),
    MIGRATED_NGAY_DU_KIEN_BAN_GIAO_KHONG_DUOC_SAU_NGAY_KET_THUC_HOP_DONG(70120, "MIGRATED NGAY DU KIEN BAN GIAO KHONG DUOC SAU NGAY KET THUC HOP DONG", "Ngày dự kiến bàn giao không được sau ngày kết thúc hợp đồng.", HttpStatus.UNPROCESSABLE_ENTITY),
    MIGRATED_CHI_NGUOI_KY_CHINH_CUA_HOP_DONG_MOI_DUOC_GHI_NHAN_Y_DINH(70121, "MIGRATED CHI NGUOI KY CHINH CUA HOP DONG MOI DUOC GHI NHAN Y DINH", "Chỉ người ký chính của hợp đồng mới được ghi nhận ý định.", HttpStatus.FORBIDDEN),
    MIGRATED_CHI_DUOC_KICH_HOAT_HOP_DONG_DANG_CHO_KY(70122, "MIGRATED CHI DUOC KICH HOAT HOP DONG DANG CHO KY", "Chỉ được kích hoạt hợp đồng đang chờ ký.", HttpStatus.BAD_REQUEST),
    MIGRATED_CAN_UPLOAD_FILE_HOP_DONG_DA_KY_TRUOC_KHI_KICH_HOAT(70123, "MIGRATED CAN UPLOAD FILE HOP DONG DA KY TRUOC KHI KICH HOAT", "Cần upload file hợp đồng đã ký trước khi kích hoạt.", HttpStatus.BAD_REQUEST),
    MIGRATED_HOP_DONG_CHUA_CO_NGUOI_KY_CHINH(70124, "MIGRATED HOP DONG CHUA CO NGUOI KY CHINH", "Hợp đồng chưa có người ký chính.", HttpStatus.BAD_REQUEST),
    MIGRATED_NGAY_BAT_DAU_KET_THUC_HOP_DONG_KHONG_HOP_LE(70125, "MIGRATED NGAY BAT DAU KET THUC HOP DONG KHONG HOP LE", "Ngày bắt đầu/kết thúc hợp đồng không hợp lệ.", HttpStatus.BAD_REQUEST),
    MIGRATED_CAN_HOAN_THANH_BAN_GIAO_PHONG_NHAP_SO_IEN_VA_UPLOAD_BIEN_6ACA66(70126, "MIGRATED CAN HOAN THANH BAN GIAO PHONG NHAP SO IEN VA UPLOAD BIEN 6ACA66", "Cần hoàn thành bàn giao phòng, nhập số điện và upload biên bản bàn giao đã ký trước khi kích hoạt hợp đồng.", HttpStatus.BAD_REQUEST),
    MIGRATED_PHONG_PHAI_O_TRANG_THAI_TRONG_HOAC_DA_DAT_COC_TRUOC_KHI__C99780(70127, "MIGRATED PHONG PHAI O TRANG THAI TRONG HOAC DA DAT COC TRUOC KHI  C99780", "Phòng phải ở trạng thái trống hoặc đã đặt cọc trước khi kích hoạt hợp đồng.", HttpStatus.BAD_REQUEST),
    MIGRATED_PHONG_DA_CO_HOP_DONG_DANG_HIEU_LUC(70128, "MIGRATED PHONG DA CO HOP DONG DANG HIEU LUC", "Phòng đã có hợp đồng đang hiệu lực.", HttpStatus.BAD_REQUEST),
    MIGRATED_VUI_LONG_HOAN_TAT_QUY_TRINH_THANH_LY_E_KICH_HOAT_HOP_ONG_AE7B70(70129, "MIGRATED VUI LONG HOAN TAT QUY TRINH THANH LY E KICH HOAT HOP ONG AE7B70", "Vui lòng hoàn tất quy trình thanh lý để kích hoạt hợp đồng thay thế.", HttpStatus.CONFLICT),
    MIGRATED_HOP_DONG_TRUOC_KHONG_CON_O_TRANG_THAI_CHO_PHEP_KICH_HOAT_011D46(70130, "MIGRATED HOP DONG TRUOC KHONG CON O TRANG THAI CHO PHEP KICH HOAT 011D46", "Hợp đồng trước không còn ở trạng thái cho phép kích hoạt gia hạn.", HttpStatus.BAD_REQUEST),
    MIGRATED_KHONG_THE_CAP_NHAT_THOI_HAN_CUA_HOP_DONG_DA_KET_THUC(70131, "MIGRATED KHONG THE CAP NHAT THOI HAN CUA HOP DONG DA KET THUC", "Không thể cập nhật thời hạn của hợp đồng đã kết thúc.", HttpStatus.BAD_REQUEST),
    MIGRATED_HOP_DONG_PHAI_GAN_VOI_PHONG(70132, "MIGRATED HOP DONG PHAI GAN VOI PHONG", "Hợp đồng phải gắn với phòng.", HttpStatus.BAD_REQUEST),
    MIGRATED_HOP_DONG_PHAI_CO_NGUOI_KY_CHINH(70133, "MIGRATED HOP DONG PHAI CO NGUOI KY CHINH", "Hợp đồng phải có người ký chính.", HttpStatus.BAD_REQUEST),
    MIGRATED_NGAY_BAT_DAU_VA_NGAY_KET_THUC_HOP_DONG_KHONG_HOP_LE(70134, "MIGRATED NGAY BAT DAU VA NGAY KET THUC HOP DONG KHONG HOP LE", "Ngày bắt đầu và ngày kết thúc hợp đồng không hợp lệ.", HttpStatus.BAD_REQUEST),
    MIGRATED_CHU_KY_THANH_TOAN_CHI_DUOC_LA_1_HOAC_3_THANG(70135, "MIGRATED CHU KY THANH TOAN CHI DUOC LA 1 HOAC 3 THANG", "Chu kỳ thanh toán chỉ được là 1 hoặc 3 tháng.", HttpStatus.BAD_REQUEST),
    MIGRATED_GIA_THUE_HANG_THANG_PHAI_LON_HON_0(70136, "MIGRATED GIA THUE HANG THANG PHAI LON HON 0", "Giá thuê hàng tháng phải lớn hơn 0.", HttpStatus.BAD_REQUEST),
    MIGRATED_TIEN_COC_KHONG_HOP_LE(70137, "MIGRATED TIEN COC KHONG HOP LE", "Tiền cọc không hợp lệ.", HttpStatus.BAD_REQUEST),
    MIGRATED_CHI_DUOC_TAO_HOP_DONG_CHO_PHONG_TRONG_SAP_TRONG_HOAC_PHO_8105F2(70138, "MIGRATED CHI DUOC TAO HOP DONG CHO PHONG TRONG SAP TRONG HOAC PHO 8105F2", "Chỉ được tạo hợp đồng cho phòng trống, sắp trống hoặc phòng đã đặt cọc.", HttpStatus.BAD_REQUEST),
    MIGRATED_SO_NGUOI_O_VUOT_QUA_SO_NGUOI_TOI_DA_CUA_PHONG(70139, "MIGRATED SO NGUOI O VUOT QUA SO NGUOI TOI DA CUA PHONG", "Số người ở vượt quá số người tối đa của phòng.", HttpStatus.BAD_REQUEST),
    MIGRATED_PHONG_SAP_TRONG_CHUA_CO_NGAY_DU_KIEN_BAN_GIAO(70140, "MIGRATED PHONG SAP TRONG CHUA CO NGAY DU KIEN BAN GIAO", "Phòng sắp trống chưa có ngày dự kiến bàn giao.", HttpStatus.CONFLICT),
    MIGRATED_NGAY_DU_KIEN_VAO_O_PHAI_SAU_HOAC_BANG_NGAY_PHONG_DU_KIEN_TRONG(70141, "MIGRATED NGAY DU KIEN VAO O PHAI SAU HOAC BANG NGAY PHONG DU KIEN TRONG", "Ngày dự kiến vào ở phải sau hoặc bằng ngày phòng dự kiến trống.", HttpStatus.UNPROCESSABLE_ENTITY),
    MIGRATED_NGAY_BAT_DAU_HOP_DONG_LA_BAT_BUOC(70142, "MIGRATED NGAY BAT DAU HOP DONG LA BAT BUOC", "Ngày bắt đầu hợp đồng là bắt buộc.", HttpStatus.BAD_REQUEST),
    MIGRATED_TIEN_COC_PHAI_LON_HON_HOAC_BANG_0(70143, "MIGRATED TIEN COC PHAI LON HON HOAC BANG 0", "Tiền cọc phải lớn hơn hoặc bằng 0.", HttpStatus.BAD_REQUEST),
    MIGRATED_HOP_DONG_CHUA_DU_THONG_TIN_NGUOI_O(70144, "MIGRATED HOP DONG CHUA DU THONG TIN NGUOI O", "Hợp đồng chưa đủ thông tin người ở.", HttpStatus.BAD_REQUEST),
    MIGRATED_MA_HOP_DONG_MOI_KHONG_DUOC_VUOT_QUA_80_KY_TU(70145, "MIGRATED MA HOP DONG MOI KHONG DUOC VUOT QUA 80 KY TU", "Mã hợp đồng mới không được vượt quá 80 ký tự.", HttpStatus.BAD_REQUEST),
    MIGRATED_MA_HOP_DONG_MOI_DA_TON_TAI(70146, "MIGRATED MA HOP DONG MOI DA TON TAI", "Mã hợp đồng mới đã tồn tại.", HttpStatus.CONFLICT),
    MIGRATED_PHONG_DANG_DUOC_DAT_TRUOC_CHO_NGUOI_KHAC_VUI_LONG_THU_LAI_SAU(70147, "MIGRATED PHONG DANG DUOC DAT TRUOC CHO NGUOI KHAC VUI LONG THU LAI SAU", "Phòng đang được đặt trước cho người khác. Vui lòng thử lại sau.", HttpStatus.CONFLICT),
    MIGRATED_PHONG_DA_CO_KHACH_KHAC_DAT_COC_GIU_CHO_KHONG_THE_GIA_HAN_BEF683(70148, "MIGRATED PHONG DA CO KHACH KHAC DAT COC GIU CHO KHONG THE GIA HAN BEF683", "Phòng đã có khách khác đặt cọc/giữ chỗ, không thể gia hạn. Vui lòng liên hệ quản lý.", HttpStatus.CONFLICT),
    MIGRATED_CHI_CHU_TRO_HOAC_QUAN_LY_MOI_CO_QUYEN_XAC_NHAN_TAI_KY_HOP_DONG(70149, "MIGRATED CHI CHU TRO HOAC QUAN LY MOI CO QUYEN XAC NHAN TAI KY HOP DONG", "Chỉ chủ trọ hoặc quản lý mới có quyền xác nhận tái ký hợp đồng.", HttpStatus.FORBIDDEN),
    MIGRATED_HOP_DONG_THUOC_YEU_CAU_CHUYEN_PHONG_VUI_LONG_XU_LY_BAN_G_91B4CB(70150, "MIGRATED HOP DONG THUOC YEU CAU CHUYEN PHONG VUI LONG XU LY BAN G 91B4CB", "Hợp đồng thuộc yêu cầu chuyển phòng; vui lòng xử lý bàn giao/kích hoạt trong luồng chuyển phòng.", HttpStatus.BAD_REQUEST),
    MIGRATED_CHUA_CO_BIEN_BAN_BAN_GIAO_DA_KY(70151, "MIGRATED CHUA CO BIEN BAN BAN GIAO DA KY", "Chưa có biên bản bàn giao đã ký.", HttpStatus.NOT_FOUND),
    MIGRATED_KHONG_TIM_THAY_BIEN_BAN_BAN_GIAO_DA_KY(70152, "MIGRATED KHONG TIM THAY BIEN BAN BAN GIAO DA KY", "Không tìm thấy biên bản bàn giao đã ký.", HttpStatus.NOT_FOUND),
    MIGRATED_CHUA_CO_BAN_HOP_DONG_THUE_DA_KY(70153, "MIGRATED CHUA CO BAN HOP DONG THUE DA KY", "Chưa có bản hợp đồng thuê đã ký.", HttpStatus.NOT_FOUND),
    MIGRATED_KHONG_TIM_THAY_FILE_HOP_DONG_THUE_DA_KY(70154, "MIGRATED KHONG TIM THAY FILE HOP DONG THUE DA KY", "Không tìm thấy file hợp đồng thuê đã ký.", HttpStatus.NOT_FOUND),
    MIGRATED_CHUA_DANG_NHAP(70155, "MIGRATED CHUA DANG NHAP", "Chưa đăng nhập.", HttpStatus.UNAUTHORIZED),
    MIGRATED_BAN_KHONG_PHAI_NGUOI_O_CUNG_CUA_HOP_DONG_NAY(70156, "MIGRATED BAN KHONG PHAI NGUOI O CUNG CUA HOP DONG NAY", "Bạn không phải người ở cùng của hợp đồng này.", HttpStatus.FORBIDDEN),
    MIGRATED_Y_DINH_NGUOI_O_CUNG_KHONG_HOP_LE(70157, "MIGRATED Y DINH NGUOI O CUNG KHONG HOP LE", "Ý định người ở cùng không hợp lệ.", HttpStatus.BAD_REQUEST),
    MIGRATED_THIEU_THONG_TIN_PHUONG_AN_SUA_CHUA(70158, "MIGRATED THIEU THONG TIN PHUONG AN SUA CHUA", "Vui lòng nhập người sửa, hạng mục và chi phí trước khi gửi phương án cho khách thuê.", HttpStatus.BAD_REQUEST),
    MIGRATED_CHI_QUYET_DINH_KHI_PHIEU_CHO_KHACH(70159, "MIGRATED CHI QUYET DINH KHI PHIEU CHO KHACH", "Chỉ được quyết định sửa chữa khi phiếu đang chờ khách thuê quyết định.", HttpStatus.BAD_REQUEST),
    MIGRATED_KHACH_THUE_PHAI_NHAP_LY_DO_KHI_KHONG_DONG_Y_SUA(70160, "MIGRATED KHACH THUE PHAI NHAP LY DO KHI KHONG DONG Y SUA", "Vui lòng nhập lý do khi không đồng ý sửa chữa.", HttpStatus.BAD_REQUEST),
    MIGRATED_CHI_BAT_DAU_XU_LY_SAU_KHI_KHACH_DONG_Y(70161, "MIGRATED CHI BAT DAU XU LY SAU KHI KHACH DONG Y", "Chỉ được bắt đầu xử lý sau khi khách thuê đã đồng ý sửa chữa.", HttpStatus.BAD_REQUEST),

    // --- INTERNAL TECHNICAL ERRORS ---
    REQUEST_CODE_ALLOCATION_FAILED(50001, "Request code allocation failed", "Không thể tạo mã yêu cầu. Vui lòng thử lại.", HttpStatus.INTERNAL_SERVER_ERROR),
    INVALID_PASSWORD_LENGTH(50002, "Invalid password length", "Độ dài mật khẩu không hợp lệ.", HttpStatus.BAD_REQUEST),
    HMAC_SECRET_INVALID(50003, "HMAC secret invalid", "Cấu hình khóa bảo mật không hợp lệ.", HttpStatus.INTERNAL_SERVER_ERROR),
    HMAC_GENERATION_FAILED(50004, "HMAC generation failed", "Không thể tạo mã xác thực.", HttpStatus.INTERNAL_SERVER_ERROR),
    SHA256_DIGEST_FAILED(50005, "SHA-256 digest failed", "Không thể tạo mã kiểm tra tệp.", HttpStatus.INTERNAL_SERVER_ERROR),
    SNOWFLAKE_CLOCK_MOVED_BACKWARDS(50006, "Snowflake clock moved backwards", "Hệ thống thời gian không hợp lệ, không thể tạo mã định danh.", HttpStatus.INTERNAL_SERVER_ERROR),
    DUPLICATE_SCHEDULED_TASK_HANDLER(50007, "Duplicate scheduled task handler", "Cấu hình tác vụ định kỳ bị trùng.", HttpStatus.INTERNAL_SERVER_ERROR),
    SCHEDULED_TASK_HANDLER_NOT_FOUND(50008, "Scheduled task handler not found", "Không tìm thấy bộ xử lý cho tác vụ định kỳ.", HttpStatus.INTERNAL_SERVER_ERROR),
    UNSUPPORTED_RECURRING_TASK(50009, "Unsupported recurring task", "Tác vụ không được hỗ trợ lịch chạy định kỳ.", HttpStatus.INTERNAL_SERVER_ERROR),
    UNSUPPORTED_NOTIFICATION_TASK(50010, "Unsupported notification task", "Loại tác vụ thông báo không được hỗ trợ.", HttpStatus.INTERNAL_SERVER_ERROR),
    ;
    int code;
    String message;
    String details;
    HttpStatusCode statusCode;
}
