package com.sep490.hdbhms.shared.exception;

import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.experimental.FieldDefaults;
import org.springframework.http.HttpStatus;
import org.springframework.http.HttpStatusCode;

@Getter
@AllArgsConstructor
@FieldDefaults(level = AccessLevel.PRIVATE, makeFinal = true)
public enum     ApiErrorCode {
    UNDEFINED(0, "Undefined", "Đã xảy ra lỗi không mong muốn. Vui lòng thử lại.", HttpStatus.INTERNAL_SERVER_ERROR),
    ACCOUNT_EXISTED(10102, "Account existed", "Tài khoản đã tồn tại.", HttpStatus.CONFLICT),
    INVALID_USERNAME(10103, "Invalid newUsername", "Tên đăng nhập phải có hơn 3 ký tự.", HttpStatus.BAD_REQUEST),
    INVALID_EMAIL(10103, "Invalid phone", "Số điện thoại không hợp lệ.", HttpStatus.BAD_REQUEST),
    INVALID_PASSWORD(10103, "Invalid password", "Mật khẩu phải có ít nhất 8 ký tự.", HttpStatus.BAD_REQUEST),
    INVALID_CREDENTIALS(10503, "Invalid credentials", "Số điện thoại hoặc mật khẩu không chính xác.", HttpStatus.UNAUTHORIZED),
    ROLE_NOT_FOUND(10103, "Role not found", "Không tìm thấy vai trò tài khoản.", HttpStatus.NOT_FOUND),
    ACCOUNT_NOT_FOUND(10201, "Account not found", "Không tìm thấy tài khoản.", HttpStatus.NOT_FOUND),
    NEW_PASSWORD_IS_EMPTY(10503, "New password is empty", "Mật khẩu mới không được để trống.", HttpStatus.BAD_REQUEST),
    OLD_PASSWORD(10103, "Old password", "Mật khẩu mới không được trùng với 3 mật khẩu cũ gần nhất.", HttpStatus.BAD_REQUEST),
    RESET_PASSWORD_NOT_ALLOWED_YET(10507, "Reset password not allowed yet", "Chưa thể đặt lại mật khẩu vào thời điểm này.", HttpStatus.FORBIDDEN),
    RESET_PASSWORD_TOKEN_EXPIRED(10503, "Reset password sessionId expired", "Phiên đặt lại mật khẩu đã hết hạn.", HttpStatus.BAD_REQUEST),
    RESET_PASSWORD_TOKEN_NOT_FOUND(10501, "Reset password sessionId not found", "Không tìm thấy phiên đặt lại mật khẩu.", HttpStatus.NOT_FOUND),
    RESET_PASSWORD_TOKEN_MISMATCH(10507, "Reset password sessionId mismatch", "Phiên đặt lại mật khẩu không thuộc tài khoản được yêu cầu.", HttpStatus.CONFLICT),
    OTP_CODE_EXPIRED_OR_MISMATCH(10507, "OTP code expired or mismatch", "Mã OTP đã hết hạn hoặc không khớp với phiên hiện tại.", HttpStatus.BAD_REQUEST),
    OTP_CODE_NOT_FOUND(10501, "OTP code not found", "Không tìm thấy mã OTP.", HttpStatus.NOT_FOUND),
    IS_OAUTH2_ACCOUNT(10507, "Is OAuth2 account", "Tài khoản OAuth2 không thể đổi mật khẩu hoặc xác thực số điện thoại.", HttpStatus.CONFLICT),
    REFRESH_TOKEN_EXPIRED(10507, "Refresh sessionId expired", "Phiên đăng nhập đã hết hạn.", HttpStatus.CONFLICT),
    ACCOUNT_IS_NOT_ACTIVE(10507, "Account is not active", "Tài khoản không ở trạng thái hoạt động nên không thể thực hiện thao tác thay đổi.", HttpStatus.FORBIDDEN),
    ACCOUNT_IS_NOT_VERIFIED(10507, "Account is not verified", "Tài khoản chưa được xác thực nên một số thao tác không khả dụng.", HttpStatus.FORBIDDEN),
    ACCOUNT_IS_ALREADY_VERIFIED(10507, "Account is already verified", "Tài khoản đã được xác thực, không thể xác thực lại.", HttpStatus.CONFLICT),
    TENANT_ACCOUNT_IDENTITY_CONFLICT(10305, "Tenant account identity conflict", "Thông tin phone/email của hồ sơ không xác định được một tài khoản duy nhất hoặc tài khoản đã thuộc hồ sơ khác.", HttpStatus.CONFLICT),
    TENANT_ACCOUNT_REACTIVATION_BLOCKED(10306, "Tenant account reactivation blocked", "Tài khoản khách thuê đang bị khóa hoặc lưu trữ nên không thể tự động kích hoạt lại.", HttpStatus.FORBIDDEN),
    SAME_USERNAME(10304, "Same newUsername", "Tên đăng nhập mới phải khác tên đăng nhập hiện tại.", HttpStatus.BAD_REQUEST),
    CHANGE_USERNAME_NOT_ALLOWED_YET(10304, "Change username not allowed yet", "Chưa thể đổi tên đăng nhập trong vòng 30 ngày kể từ lần đổi gần nhất.", HttpStatus.BAD_REQUEST),
    CHANGE_EMAIL_NOT_ALLOWED_YET(10304, "Change phone not allowed yet", "Chưa thể đổi số điện thoại trong vòng 48 giờ kể từ lần đổi gần nhất.", HttpStatus.BAD_REQUEST),
    SAME_EMAIL(10304, "Same phone", "Số điện thoại mới phải khác số điện thoại hiện tại.", HttpStatus.BAD_REQUEST),
    SAME_PASSWORD(10304, "Same password", "Mật khẩu mới phải khác mật khẩu hiện tại.", HttpStatus.BAD_REQUEST),
    SAME_ROLE(10304, "Same role", "Vai trò mới phải khác vai trò hiện tại.", HttpStatus.BAD_REQUEST),
    SAME_STATUS(10304, "Same status", "Trạng thái mới phải khác trạng thái hiện tại.", HttpStatus.BAD_REQUEST),
    INVALID_JWT_TOKEN(10507, "Invalid JWT sessionId", "Không thể xác thực phiên đăng nhập.", HttpStatus.INTERNAL_SERVER_ERROR),
    UNAUTHENTICATED(10505, "Unauthenticated", "Phiên đăng nhập đã hết hạn.", HttpStatus.UNAUTHORIZED),
    UNAUTHORIZED(10504, "Unauthorized", "Bạn không có quyền thực hiện thao tác này", HttpStatus.FORBIDDEN),
    CURRENT_EMAIL_PASSWORD_INVALID(10503, "Current email password invalid", "Mật khẩu hiện tại không đúng", HttpStatus.BAD_REQUEST),
    CURRENT_PASSWORD_INVALID(10503, "Current password invalid", "Mật khẩu hiện tại không đúng", HttpStatus.BAD_REQUEST),
    FIRST_PASSWORD_CHANGE_NOT_REQUIRED(10304, "First password change not required", "Tài khoản không yêu cầu đổi mật khẩu lần đầu", HttpStatus.BAD_REQUEST),
    FORBIDDEN_OPERATION(10504, "Forbidden operation", "Bạn không có quyền thực hiện thao tác này", HttpStatus.FORBIDDEN),
    INVALID_REQUEST(10103, "Invalid request", "Yêu cầu không hợp lệ", HttpStatus.BAD_REQUEST),
    INVALID_REQUEST_PAYLOAD(10103, "Invalid request payload", "Dữ liệu đặt cọc không đúng định dạng. Vui lòng kiểm tra lại thông tin.", HttpStatus.BAD_REQUEST),
    OPERATION_CONFLICT(10304, "Operation conflict", "Thao tác bị xung đột", HttpStatus.CONFLICT),
    RESOURCE_NOT_FOUND(10201, "Resource not found", "Không tìm thấy tài nguyên", HttpStatus.NOT_FOUND),

    // --- STANDARDIZED BUSINESS VALIDATION ---
    ACCOUNT_NOT_FOUND_BY_EMAIL(10201, "Account not found by email", "Không tìm thấy tài khoản với email đã nhập.", HttpStatus.NOT_FOUND),
    STAFF_EMAIL_ALREADY_USED(10304, "Staff email already used", "Email đã được sử dụng", HttpStatus.CONFLICT),
    INVALID_TENANT_PROFILE_ACCESS_REQUEST(10103, "Invalid tenant profile access request", "Yêu cầu cấp quyền hồ sơ khách thuê không hợp lệ.", HttpStatus.BAD_REQUEST),
    INVALID_PERMISSION_ACCESS_REQUEST(10103, "Invalid permission access request", "Yêu cầu cấp quyền không hợp lệ.", HttpStatus.BAD_REQUEST),
    PERMISSION_GRANT_NOT_FOUND(10203, "Permission grant not found", "Không tìm thấy quyền truy cập.", HttpStatus.NOT_FOUND),
    INVALID_PERMISSION_GRANT_DURATION(10103, "Invalid permission grant duration", "Thời hạn cấp quyền không hợp lệ", HttpStatus.BAD_REQUEST),
    CURRENT_CONTRACT_NOT_FOUND(40701, "Current contract not found", "Không tìm thấy hợp đồng hiện tại", HttpStatus.NOT_FOUND),
    TRANSFER_TARGET_ROOM_NOT_FOUND(40401, "Transfer target room not found", "Không tìm thấy phòng muốn chuyển đến", HttpStatus.NOT_FOUND),
    NOMINATED_PERSON_NOT_FOUND(10202, "Nominated person not found", "Không tìm thấy người được đề cử", HttpStatus.NOT_FOUND),
    TRANSFER_CONTRACT_NOT_IN_SIGNING_SET(10103, "Transfer contract not in signing set", "Hợp đồng này không thuộc bộ hợp đồng cần ký của yêu cầu chuyển phòng.", HttpStatus.BAD_REQUEST),
    SIGNED_TRANSFER_CONTRACT_FILE_REQUIRED(10103, "Signed transfer contract file required", "Vui lòng upload file hợp đồng đã ký trước khi xác nhận đã ký.", HttpStatus.BAD_REQUEST),
    SIGNED_TRANSFER_CONTRACTS_REQUIRED_FOR_COMPLETION(10103, "Signed transfer contracts required for completion", "Vui lòng upload file hợp đồng đã ký trước khi xác nhận đủ bộ.", HttpStatus.BAD_REQUEST),
    TRANSFER_CONTRACTS_MUST_BE_CONFIRMED_INDIVIDUALLY(10103, "Transfer contracts must be confirmed individually", "Vui lòng xác nhận từng hợp đồng đã ký trước khi xác nhận đủ bộ.", HttpStatus.BAD_REQUEST),
    HOLDER_REPLACEMENT_OCCUPANTS_REQUIRED(10103, "Holder replacement occupants required", "Cần xác định người rời đi và người ở lại.", HttpStatus.BAD_REQUEST),
    CURRENT_PRIMARY_TENANT_MUST_LEAVE(10103, "Current primary tenant must leave", "Người đứng tên hiện tại phải nằm trong danh sách người rời đi.", HttpStatus.BAD_REQUEST),
    REPLACEMENT_PRIMARY_TENANT_MUST_STAY(10103, "Replacement primary tenant must stay", "Người đứng tên mới phải nằm trong danh sách người ở lại.", HttpStatus.BAD_REQUEST),
    HOLDER_REPLACEMENT_OCCUPANTS_OVERLAP(10103, "Holder replacement occupants overlap", "Danh sách người rời đi và người ở lại không được trùng nhau.", HttpStatus.BAD_REQUEST),
    HOLDER_REPLACEMENT_OCCUPANTS_UNCLASSIFIED(10103, "Holder replacement occupants unclassified", "Tất cả người đang ở phải được phân loại là rời đi hoặc ở lại.", HttpStatus.BAD_REQUEST),
    REPLACEMENT_PRIMARY_TENANT_NOT_ACTIVE(10103, "Replacement primary tenant not active", "Người đứng tên mới phải là người đang ở trong hợp đồng.", HttpStatus.BAD_REQUEST),

    MD5_DIGEST_ERROR(30203, "MD5 digest error", "Đã xảy ra lỗi khi tạo mã MD5 cho tệp.", HttpStatus.INTERNAL_SERVER_ERROR),
    VISIT_001(40101, "Visit request not found", "Không tìm thấy lịch xem phòng", HttpStatus.NOT_FOUND),
    VISIT_002(40102, "Invalid room property", "Phòng không thuộc cơ sở đã chọn", HttpStatus.BAD_REQUEST),
    VISIT_003(40103, "Invalid phone", "Số điện thoại không hợp lệ", HttpStatus.BAD_REQUEST),
    VISIT_004(40104, "Invalid visit status", "Trạng thái không hợp lệ", HttpStatus.BAD_REQUEST),
    VISIT_005(40105, "Visit request access denied", "Không có quyền thao tác", HttpStatus.FORBIDDEN),
    VISIT_006(40106, "Missing required visit request field", "Thiếu thông tin bắt buộc", HttpStatus.BAD_REQUEST),
    VISIT_007(40107, "Invalid appointment time", "Ngày giờ hẹn xem phải sau thời gian hiện tại", HttpStatus.BAD_REQUEST),
    VISIT_008(40108, "Room unavailable for viewing", "Chỉ được chọn phòng đang trống hoặc sắp trống tại thời điểm tạo/sửa lịch xem phòng", HttpStatus.BAD_REQUEST),
    VISIT_009(40109, "Room viewing date too early", "Ngày xem phòng sắp trống phải sau ngày khách cũ chuyển đi", HttpStatus.BAD_REQUEST),
    DEPOSIT_001(40201, "Invalid deposit occupancy", "Thông tin số người ở không hợp lệ", HttpStatus.BAD_REQUEST),
    HANDOVER_001(40301, "Handover already confirmed", "Biên bản bàn giao đã được xác nhận", HttpStatus.BAD_REQUEST),

    // --- PORTAL & FILE (20xxx) ---
    HOME_DATA_NOT_FOUND(20101, "Home data not found", "Không tìm thấy dữ liệu trang chủ", HttpStatus.NOT_FOUND),
    FILE_UPLOAD_FAILED(20201, "File upload failed", "Tải tệp lên thất bại", HttpStatus.INTERNAL_SERVER_ERROR),
    FILE_DOWNLOAD_FAILED(20202, "File download failed", "Tải tệp xuống thất bại", HttpStatus.INTERNAL_SERVER_ERROR),

    // --- IDENTITY & ACCESS (10xxx) ---
    USER_PROFILE_NOT_FOUND(10202, "User profile not found", "Không tìm thấy hồ sơ người dùng", HttpStatus.NOT_FOUND),
    PERMISSION_REQUEST_NOT_FOUND(10203, "Permission request not found", "Không tìm thấy yêu cầu cấp quyền", HttpStatus.NOT_FOUND),
    EMERGENCY_CONTACT_NOT_FOUND(10204, "Emergency contact not found", "Không tìm thấy liên hệ khẩn cấp", HttpStatus.NOT_FOUND),
    IDENTITY_DOCUMENT_NOT_FOUND(10205, "Identity document not found", "Không tìm thấy giấy tờ tùy thân", HttpStatus.NOT_FOUND),

    // --- OCCUPANCY: PROPERTY & ROOM (404xx) ---
    ROOM_NOT_FOUND(40401, "Room not found", "Không tìm thấy phòng", HttpStatus.NOT_FOUND),
    ROOM_ASSET_NOT_FOUND(40402, "Room asset not found", "Không tìm thấy thiết bị phòng", HttpStatus.NOT_FOUND),
    FLOOR_NOT_FOUND(40403, "Floor not found", "Không tìm thấy tầng", HttpStatus.NOT_FOUND),
    PROPERTY_NOT_FOUND(40404, "Property not found", "Không tìm thấy cơ sở", HttpStatus.NOT_FOUND),
    PROPERTY_RULE_NOT_FOUND(40405, "Property rule not found", "Không tìm thấy nội quy", HttpStatus.NOT_FOUND),
    ROOM_HOLD_NOT_FOUND(40406, "Room hold not found", "Không tìm thấy thông tin giữ phòng", HttpStatus.NOT_FOUND),
    ROOM_IMAGE_NOT_FOUND(40407, "Room image not found", "Không tìm thấy ảnh phòng", HttpStatus.NOT_FOUND),
    PROPERTY_IMAGE_NOT_FOUND(40408, "Property image not found", "Không tìm thấy ảnh cơ sở", HttpStatus.NOT_FOUND),
    ROOM_STATUS_HISTORY_NOT_FOUND(40409, "Room status history not found", "Không tìm thấy lịch sử trạng thái phòng", HttpStatus.NOT_FOUND),
    ROOM_TRANSFER_REQUEST_NOT_FOUND(40410, "Room transfer request not found", "Không tìm thấy yêu cầu chuyển phòng", HttpStatus.NOT_FOUND),

    ROOM_TRANSFER_INVALID_STATE(40415, "Room transfer invalid state", "Yêu cầu chuyển phòng đang ở trạng thái %s; cần một trong: %s.", HttpStatus.UNPROCESSABLE_ENTITY),
    ROOM_TRANSFER_HANDOVER_ASSETS_REQUIRED(40416, "Room transfer handover assets required", "Phải nhập danh sách tài sản bàn giao khi phòng cũ trả trống.", HttpStatus.BAD_REQUEST),
    ROOM_TRANSFER_HANDOVER_ELECTRICITY_REQUIRED(40417, "Room transfer handover electricity required", "Phải nhập chỉ số điện khi bàn giao phòng.", HttpStatus.BAD_REQUEST),
    ROOM_TRANSFER_HANDOVER_DATE_INVALID(40418, "Room transfer handover date invalid", "Ngày %s không hợp lệ hoặc không được nằm trong tương lai.", HttpStatus.BAD_REQUEST),
    ROOM_TRANSFER_METER_READING_INVALID(40419, "Room transfer meter reading invalid", "Chỉ số điện bàn giao không hợp lệ hoặc nhỏ hơn chỉ số trước đó.", HttpStatus.BAD_REQUEST),
    ROOM_TRANSFER_DIFFERENCE_PAYMENT_REQUIRED(40420, "Room transfer difference payment required", "Khoản chênh lệch chuyển phòng chưa được thanh toán.", HttpStatus.UNPROCESSABLE_ENTITY),
    ROOM_TRANSFER_SETTLEMENT_REQUIRED(40421, "Room transfer settlement required", "Phải chọn phương án xử lý khoản chênh lệch chuyển phòng.", HttpStatus.BAD_REQUEST),
    ROOM_TRANSFER_SETTLEMENT_INVALID(40422, "Room transfer settlement invalid", "Phương án xử lý khoản chênh lệch chuyển phòng không phù hợp.", HttpStatus.BAD_REQUEST),
    ROOM_TRANSFER_CONTRACT_STATE_INVALID(40423, "Room transfer contract state invalid", "Hợp đồng %s đang ở trạng thái %s, không thể thực hiện bước này.", HttpStatus.UNPROCESSABLE_ENTITY),
    ROOM_TRANSFER_HOLDER_NOMINATION_REQUIRED(40424, "Room transfer holder nomination required", "Phải xác định người đứng tên thay thế trước khi tiếp tục.", HttpStatus.UNPROCESSABLE_ENTITY),
    ROOM_TRANSFER_TARGET_ROOM_INVALID(40425, "Room transfer target room invalid", "Phòng đích đang ở trạng thái %s nên không thể chuyển phòng.", HttpStatus.CONFLICT),
    ROOM_TRANSFER_TARGET_CAPACITY_EXCEEDED(40426, "Room transfer target capacity exceeded", "Phòng đích không đủ sức chứa cho số người chuyển đến.", HttpStatus.CONFLICT),
    ROOM_TRANSFER_OPEN_REQUEST_EXISTS(40427, "Room transfer open request exists", "Hợp đồng này đã có một yêu cầu chuyển phòng đang được xử lý.", HttpStatus.CONFLICT),
    ROOM_TRANSFER_SOURCE_TARGET_SAME(40428, "Room transfer source and target are the same", "Phòng đích phải khác phòng hiện tại.", HttpStatus.BAD_REQUEST),
    ROOM_TRANSFER_HANDOVER_NOT_CONFIRMED(40429, "Room transfer handover not confirmed", "Biên bản bàn giao %s chưa được xác nhận hoặc chưa có chỉ số điện.", HttpStatus.UNPROCESSABLE_ENTITY),
    ROOM_TRANSFER_FINAL_INVOICE_UNPAID(40430, "Room transfer final invoice unpaid", "Hóa đơn %s chưa được thanh toán.", HttpStatus.UNPROCESSABLE_ENTITY),
    ROOM_TRANSFER_TARGET_HOLDER_APPROVAL_REQUIRED(40431, "Room transfer target holder approval required", "Chủ phòng đích chưa phê duyệt yêu cầu chuyển phòng.", HttpStatus.UNPROCESSABLE_ENTITY),
    ROOM_TRANSFER_COMPENSATION_NOT_ALLOWED(40432, "Room transfer compensation not allowed", "Chỉ được nhập bồi thường khi phòng cũ được trả trống hoàn toàn.", HttpStatus.BAD_REQUEST),
    ROOM_TRANSFER_TYPE_INVALID(40433, "Room transfer type invalid", "Loại chuyển phòng không hợp lệ cho bước hiện tại.", HttpStatus.UNPROCESSABLE_ENTITY),
    ROOM_TRANSFER_DATE_INVALID(40434, "Room transfer date invalid", "Tháng chuyển phòng không hợp lệ.", HttpStatus.BAD_REQUEST),
    ROOM_TRANSFER_SOURCE_CONTRACT_INVALID(40435, "Room transfer source contract invalid", "Hợp đồng phòng cũ không ở trạng thái đang hiệu lực hoặc người yêu cầu không phải người ở.", HttpStatus.UNPROCESSABLE_ENTITY),
    ROOM_TRANSFER_PARTICIPANT_INVALID(40436, "Room transfer participant invalid", "Người dùng hiện tại không phải người tham gia hợp lệ của yêu cầu chuyển phòng.", HttpStatus.FORBIDDEN),
    ROOM_HANDOVER_REQUIRES_VACANT_ROOM(40441, "Room handover requires vacant room", "Phòng đặt trước vào phòng sắp trống chỉ được bàn giao khi phòng đã ở trạng thái trống.", HttpStatus.CONFLICT),
    ROOM_LIQUIDATION_BLOCKED_BY_BOOKING(40442, "Room liquidation blocked by booking", "Không thể thanh lý vì phòng sắp trống đã có khách khác đặt hoặc giữ chỗ.", HttpStatus.CONFLICT),
    ROOM_CO_OCCUPANT_ADD_BLOCKED_BY_BOOKING(40443, "Co-occupant addition blocked by booking", "Không thể thêm người ở cùng vì phòng sắp trống đã có khách khác đặt hoặc giữ chỗ.", HttpStatus.CONFLICT),
    ROOM_TRANSFER_ALL_OCCUPANTS_REQUIRED(40444, "All occupants must transfer", "Phòng sắp trống đã có khách khác đặt hoặc giữ chỗ; bắt buộc chuyển toàn bộ người đang ở.", HttpStatus.CONFLICT),
    ROOM_TRANSFER_MINIMUM_TENURE_NOT_REACHED(40445, "Room transfer minimum tenure not reached", "Chưa đủ 2/3 thời hạn hợp đồng để thực hiện chuyển phòng.", HttpStatus.CONFLICT),
    ROOM_TRANSFER_INVOICE_NOT_FOUND(40437, "Room transfer invoice not found", "Không tìm thấy hóa đơn phát sinh trong luồng chuyển phòng.", HttpStatus.NOT_FOUND),

    // --- OCCUPANCY: LEASE & CONTRACT (407xx) ---
    LIQUIDATION_DEPOSIT_FORFEITURE_CONFIRMATION_REQUIRED(70130, "Tenant deposit forfeiture confirmation required", "Vui lòng chờ khách thuê xác nhận chấp nhận khoản mất cọc trước khi thanh lý hợp đồng.", HttpStatus.CONFLICT),
    CONTRACT_NOT_FOUND(40701, "Contract not found", "Không tìm thấy hợp đồng", HttpStatus.NOT_FOUND),
    CONTRACT_EVENT_NOT_FOUND(40702, "Contract event not found", "Không tìm thấy sự kiện hợp đồng", HttpStatus.NOT_FOUND),
    CONTRACT_HANDOVER_ITEM_NOT_FOUND(40703, "Handover item not found", "Không tìm thấy thiết bị bàn giao", HttpStatus.NOT_FOUND),
    CONTRACT_HANDOVER_RECORD_NOT_FOUND(40704, "Handover record not found", "Không tìm thấy biên bản bàn giao", HttpStatus.NOT_FOUND),
    CONTRACT_LIQUIDATION_NOT_FOUND(40705, "Liquidation not found", "Không tìm thấy biên bản thanh lý", HttpStatus.NOT_FOUND),
    CONTRACT_OCCUPANT_NOT_FOUND(40706, "Occupant not found", "Không tìm thấy người ở", HttpStatus.NOT_FOUND),
    CONTRACT_TERMINATION_NOTICE_NOT_FOUND(40707, "Termination notice not found", "Không tìm thấy thông báo chấm dứt", HttpStatus.NOT_FOUND),
    TENANT_NOT_FOUND(40708, "Tenant not found", "Không tìm thấy người thuê", HttpStatus.NOT_FOUND),
    LEAD_NOT_FOUND(40709, "Lead not found", "Không tìm thấy khách hàng tiềm năng", HttpStatus.NOT_FOUND),
    RULE_VIOLATION_NOT_FOUND(40710, "Rule violation not found", "Không tìm thấy vi phạm nội quy", HttpStatus.NOT_FOUND),
    PENDING_CONTRACT_EXISTS(40711, "Pending contract exists", "Phòng %s đã có hợp đồng %s đang ở trạng thái %s.", HttpStatus.CONFLICT),

    CONTRACT_ACTIVATION_STATUS_INVALID(40713, "Contract activation status invalid", "Không thể kích hoạt hợp đồng từ trạng thái %s.", HttpStatus.BAD_REQUEST),
    CONTRACT_SIGNED_FILE_REQUIRED(40714, "Signed contract file required", "Cần có file hợp đồng đã ký trước khi kích hoạt.", HttpStatus.BAD_REQUEST),
    CONTRACT_PRIMARY_TENANT_REQUIRED(40715, "Primary tenant required", "Cần có người đứng tên chính trước khi kích hoạt hợp đồng.", HttpStatus.BAD_REQUEST),
    CONTRACT_DATES_INVALID(40716, "Contract dates invalid", "Ngày bắt đầu và ngày kết thúc hợp đồng không hợp lệ.", HttpStatus.BAD_REQUEST),
    CONTRACT_ROOM_REQUIRED(40717, "Contract room required", "Hợp đồng phải được gắn với một phòng trước khi kích hoạt.", HttpStatus.BAD_REQUEST),
    CONTRACT_ROOM_STATUS_INVALID(40718, "Contract room status invalid", "Không thể kích hoạt hợp đồng khi phòng đang ở trạng thái %s.", HttpStatus.BAD_REQUEST),
    CONTRACT_PREVIOUS_STATUS_INVALID(40719, "Previous contract status invalid", "Không thể tái ký hợp đồng cũ từ trạng thái %s.", HttpStatus.BAD_REQUEST),
    CONTRACT_OUTSTANDING_DEBT(40726, "Contract has outstanding debt", "Hợp đồng còn công nợ %s VNĐ. Vui lòng thanh toán hết công nợ trước khi thực hiện thao tác.", HttpStatus.CONFLICT),
    CONTRACT_ACTIVATION_READING_REQUIRED(40720, "Contract activation reading required", "Cần nhập chỉ số điện đầu kỳ trước khi kích hoạt hợp đồng.", HttpStatus.BAD_REQUEST),
    CONTRACT_ACTIVATION_READING_INVALID(40721, "Contract activation reading invalid", "Chỉ số điện đầu kỳ (%s) không được nhỏ hơn chỉ số mới nhất (%s).", HttpStatus.BAD_REQUEST),
    CONTRACT_TRANSFER_WORKFLOW_CONFLICT(40722, "Contract transfer workflow conflict", "Hợp đồng đang thuộc một luồng chuyển phòng chưa hoàn tất.", HttpStatus.CONFLICT),
    CONTRACT_HANDOVER_TYPE_INVALID(40723, "Contract handover type invalid", "Loại bàn giao không phù hợp với endpoint này.", HttpStatus.BAD_REQUEST),
    CONTRACT_HANDOVER_ELECTRICITY_REQUIRED(40724, "Contract handover electricity required", "Phải nhập chỉ số điện khi bàn giao hợp đồng.", HttpStatus.BAD_REQUEST),
    CONTRACT_HANDOVER_DEPOSIT_SETTLEMENT_REQUIRED(40725, "Move-out handover requires deposit settlement", "Vui lòng hoàn tất hoàn cọc hoặc xác nhận mất cọc trước khi bàn giao trả phòng.", HttpStatus.CONFLICT),

    // --- OCCUPANCY: DEPOSIT (402xx) ---
    DEPOSIT_AGREEMENT_NOT_FOUND(40201, "Deposit agreement not found", "Không tìm thấy thỏa thuận cọc", HttpStatus.NOT_FOUND),
    DEPOSIT_FORM_NOT_FOUND(40202, "Deposit form not found", "Không tìm thấy biểu mẫu cọc", HttpStatus.NOT_FOUND),
    DEPOSIT_EXTENSION_EVENT_NOT_FOUND(40203, "Deposit extension not found", "Không tìm thấy gia hạn cọc", HttpStatus.NOT_FOUND),
    DEPOSIT_AGREEMENT_CONTRACT_NOT_FOUND(40204, "Deposit agreement contract not found", "Không tìm thấy hợp đồng đặt cọc.", HttpStatus.NOT_FOUND),
    DEPOSIT_FORM_FOR_UPDATE_NOT_FOUND(40205, "Deposit form for update not found", "Không tìm thấy form đặt cọc để cập nhật thông tin khách.", HttpStatus.BAD_REQUEST),
    DEPOSIT_BATCH_NOT_FOUND(40206, "Deposit batch not found", "Không tìm thấy batch đặt cọc.", HttpStatus.NOT_FOUND),
    DEPOSIT_ALREADY_PAID(40207, "Deposit already paid", "Phòng đã được đặt cọc thành công, không thể hủy giữ chỗ.", HttpStatus.CONFLICT),
    DEPOSIT_BATCH_ALREADY_PAID(40208, "Deposit batch already paid", "Batch đã thanh toán thành công, không thể hủy giữ chỗ.", HttpStatus.CONFLICT),
    DEPOSIT_STATUS_INVALID(40209, "Invalid deposit status", "Trạng thái cọc không hợp lệ. Mất cọc phải được xử lý qua hành động có kiểm tra quá hạn.", HttpStatus.BAD_REQUEST),
    DEPOSIT_ADDRESS_REQUIRED(40210, "Deposit address required", "Địa chỉ không được để trống.", HttpStatus.BAD_REQUEST),
    DEPOSIT_PHONE_INVALID(40211, "Invalid deposit phone", "Số điện thoại phải gồm 10 chữ số và bắt đầu bằng 0", HttpStatus.BAD_REQUEST),
    DEPOSIT_LEASE_SIGN_DATE_PAST(40212, "Deposit lease sign date in past", "Ngày ký hợp đồng dự kiến không được là ngày quá khứ.", HttpStatus.BAD_REQUEST),
    DEPOSIT_MOVE_IN_DATE_PAST(40213, "Deposit move-in date in past", "Ngày vào ở dự kiến không được là ngày quá khứ.", HttpStatus.BAD_REQUEST),
    DEPOSIT_MOVE_IN_BEFORE_SIGN_DATE(40214, "Deposit move-in before sign date", "Ngày vào ở dự kiến không được trước ngày ký hợp đồng dự kiến.", HttpStatus.BAD_REQUEST),
    DEPOSIT_PAID_DATES_IMMUTABLE(40215, "Paid deposit dates immutable", "Ngày hẹn của cọc đã thanh toán chỉ được thay đổi qua hành động gia hạn.", HttpStatus.BAD_REQUEST),
    DEPOSIT_MANAGEMENT_UPDATE_NOT_ALLOWED(40216, "Deposit management update not allowed", "Chỉ được cập nhật thông tin khi cọc đang chờ thanh toán, đã đặt cọc, đang giữ cọc hoặc chờ ký hợp đồng.", HttpStatus.BAD_REQUEST),
    DEPOSIT_LIFECYCLE_TERMINAL(40217, "Deposit lifecycle terminal", "Không thể thay đổi khoản cọc đã kết thúc xử lý.", HttpStatus.BAD_REQUEST),
    DEPOSIT_CONTACT_NOT_ALLOWED(40218, "Deposit contact not allowed", "Chỉ ghi nhận liên hệ cho khoản cọc đang giữ chỗ.", HttpStatus.BAD_REQUEST),
    DEPOSIT_CONTACT_DATE_NOT_REACHED(40219, "Deposit contact date not reached", "Chỉ liên hệ xử lý từ ngày khách dự kiến vào ở.", HttpStatus.BAD_REQUEST),
    DEPOSIT_FORFEITURE_NOT_ELIGIBLE(40220, "Deposit forfeiture not eligible", "Chỉ được xử lý mất cọc sau 14 ngày quá hạn và lần liên hệ gần nhất ghi nhận không liên lạc được.", HttpStatus.BAD_REQUEST),
    DEPOSIT_EXTENSION_INVALID(40221, "Invalid deposit extension", "Thông tin gia hạn phiếu cọc không hợp lệ.", HttpStatus.BAD_REQUEST),
    DEPOSIT_ROOM_LIST_EMPTY(40222, "Deposit room list empty", "Phải có ít nhất 1 phòng để đặt cọc.", HttpStatus.BAD_REQUEST),
    DEPOSIT_ROOM_LIST_DUPLICATED(40223, "Deposit room list duplicated", "Danh sách phòng có roomId trùng lặp.", HttpStatus.BAD_REQUEST),
    DEPOSIT_ROOMS_DIFFERENT_PROPERTY(40224, "Deposit rooms belong to different properties", "Các phòng trong batch phải cùng một cơ sở.", HttpStatus.BAD_REQUEST),
    DEPOSIT_OCCUPANT_LIMIT_EXCEEDED(40225, "Deposit occupant limit exceeded", "Số người ở không hợp lệ.", HttpStatus.BAD_REQUEST),
    DEPOSIT_EXPECTED_DATE_IN_PAST(40226, "Deposit expected date in past", "Ngày dự kiến không được trước ngày hiện tại.", HttpStatus.BAD_REQUEST),
    DEPOSIT_PAYMENT_CYCLE_INVALID(40227, "Invalid deposit payment cycle", "Chu kỳ thanh toán chỉ được là 1 hoặc 3 tháng.", HttpStatus.BAD_REQUEST),
    DEPOSIT_EXPECTED_MOVE_IN_BEFORE_SIGN_DATE(40228, "Expected move-in before sign date", "Ngày dự kiến vào ở không được trước ngày hẹn ký hợp đồng.", HttpStatus.UNPROCESSABLE_ENTITY),
    DEPOSIT_EXPECTED_SIGN_DATE_BEFORE_VACANT_DATE(40229, "Expected sign date before vacant date", "Ngày hẹn ký hợp đồng phải sau hoặc bằng ngày phòng dự kiến trống.", HttpStatus.UNPROCESSABLE_ENTITY),
    DEPOSIT_EXPECTED_MOVE_IN_BEFORE_VACANT_DATE(40230, "Expected move-in before vacant date", "Ngày dự kiến vào ở phải sau hoặc bằng ngày phòng dự kiến trống.", HttpStatus.UNPROCESSABLE_ENTITY),
    DEPOSIT_EXPECTED_MOVE_IN_REQUIRED(40231, "Expected move-in date required", "Cần có ngày dự kiến vào ở.", HttpStatus.UNPROCESSABLE_ENTITY),
    DEPOSIT_EXPECTED_SIGN_DATE_REQUIRED(40232, "Expected sign date required", "Cần có ngày dự kiến ký hợp đồng.", HttpStatus.UNPROCESSABLE_ENTITY),
    DEPOSIT_EXPECTED_VACANT_DATE_MISSING(40233, "Expected vacant date missing", "Phòng sắp trống chưa có ngày dự kiến bàn giao.", HttpStatus.UNPROCESSABLE_ENTITY),
    DEPOSIT_EXPECTED_MOVE_IN_TOO_FAR(40234, "Expected move-in date too far", "Ngày dự kiến vào ở chỉ được tối đa 14 ngày kể từ hôm nay.", HttpStatus.UNPROCESSABLE_ENTITY),
    DEPOSIT_EXPECTED_SIGN_DATE_TOO_FAR(40235, "Expected sign date too far", "Ngày hẹn ký hợp đồng chỉ được tối đa 14 ngày kể từ hôm nay.", HttpStatus.UNPROCESSABLE_ENTITY),
    DEPOSIT_EXPECTED_MOVE_IN_TOO_FAR_AFTER_VACANT(40236, "Expected move-in date too far after vacant date", "Ngày dự kiến vào ở chỉ được tối đa 14 ngày kể từ ngày khách cũ trả phòng.", HttpStatus.UNPROCESSABLE_ENTITY),
    DEPOSIT_EXPECTED_SIGN_DATE_TOO_FAR_AFTER_VACANT(40237, "Expected sign date too far after vacant date", "Ngày hẹn ký hợp đồng chỉ được tối đa 14 ngày kể từ ngày khách cũ trả phòng.", HttpStatus.UNPROCESSABLE_ENTITY),
    DEPOSIT_FILE_UPLOAD_REQUIRED(40238, "Deposit file upload required", "Thiếu file CCCD hoặc ảnh chân dung.", HttpStatus.BAD_REQUEST),
    DEPOSIT_FILE_UPLOAD_FAILED(40239, "Deposit file upload failed", "Không thể upload file định danh.", HttpStatus.BAD_REQUEST),
    DEPOSIT_PAYMENT_INIT_FAILED(40240, "Deposit payment initialization failed", "Không thể khởi tạo thanh toán. Vui lòng thử lại.", HttpStatus.BAD_GATEWAY),
    BATCH_ROOM_UNAVAILABLE(40241, "Batch room unavailable", "Một số phòng đã có người đặt cọc hoặc đang được xử lý.", HttpStatus.CONFLICT),

    // --- OCCUPANCY: UTILITY & METER (409xx) ---
    METER_NOT_FOUND(40901, "Meter not found", "Không tìm thấy đồng hồ", HttpStatus.NOT_FOUND),
    METER_READING_NOT_FOUND(40902, "Meter reading not found", "Không tìm thấy chỉ số đồng hồ", HttpStatus.NOT_FOUND),
    METER_READING_BATCH_NOT_FOUND(40903, "Meter reading batch not found", "Không tìm thấy đợt chốt điện nước", HttpStatus.NOT_FOUND),
    METER_READING_IMPORT_ROW_NOT_FOUND(40904, "Meter reading import row not found", "Không tìm thấy dòng import", HttpStatus.NOT_FOUND),
    METER_READING_ANOMALY_NOT_FOUND(40905, "Meter reading anomaly not found", "Không tìm thấy bất thường chỉ số", HttpStatus.NOT_FOUND),
    UTILITY_TARIFF_NOT_FOUND(40906, "Utility tariff not found", "Không tìm thấy bảng giá điện nước", HttpStatus.NOT_FOUND),
    INVALID_METER_READING_VALUE(40907, "Invalid meter reading value", "Chỉ số mới không được nhỏ hơn chỉ số cũ", HttpStatus.BAD_REQUEST),
    METER_READING_BATCH_CANCELLED(40908, "Meter reading batch cancelled", "Đợt chốt điện nước đã bị hủy", HttpStatus.BAD_REQUEST),
    METER_READING_ROOM_NOT_ELIGIBLE(40909, "Meter reading room not eligible", "Phòng không có hợp đồng thuê phát sinh trong kỳ", HttpStatus.BAD_REQUEST),
    METER_READING_NO_ELIGIBLE_ROOMS(40910, "No rooms require meter reading", "Không có phòng cần chốt điện nước trong kỳ này", HttpStatus.BAD_REQUEST),
    METER_READING_BATCH_CONFIRMED(40911, "Meter reading batch confirmed", "Kỳ ghi chỉ số đã chốt, không thể chỉnh sửa", HttpStatus.BAD_REQUEST),
    METER_READING_INVOICES_ISSUED(40927, "Meter reading invoices issued", "Hóa đơn của kỳ này đã phát hành, không thể chỉnh sửa chỉ số điện.", HttpStatus.BAD_REQUEST),
    METER_READING_EXCEL_FILE_REQUIRED(40912, "Meter reading Excel file required", "Vui lòng chọn file Excel cần nhập chỉ số điện.", HttpStatus.BAD_REQUEST),
    METER_READING_EXCEL_XLSX_REQUIRED(40913, "Meter reading Excel xlsx required", "File nhập chỉ số điện phải có định dạng .xlsx.", HttpStatus.BAD_REQUEST),
    METER_READING_EXCEL_WORKBOOK_EMPTY(40914, "Meter reading Excel workbook empty", "File Excel không có trang tính để nhập chỉ số điện.", HttpStatus.BAD_REQUEST),
    METER_READING_EXCEL_ROOM_COLUMN_MISSING(40915, "Meter reading Excel room column missing", "Không tìm thấy cột mã phòng trong file Excel.", HttpStatus.BAD_REQUEST),
    METER_READING_EXCEL_VALUE_COLUMN_MISSING(40916, "Meter reading Excel value column missing", "Không tìm thấy cột chỉ số điện mới trong file Excel.", HttpStatus.BAD_REQUEST),
    METER_READING_EXCEL_REQUIRED_COLUMNS_MISSING(40917, "Meter reading Excel required columns missing", "File Excel phải có cột mã phòng và cột chỉ số điện mới.", HttpStatus.BAD_REQUEST),
    METER_READING_EXCEL_NO_DATA(40918, "Meter reading Excel no data", "File Excel không có dòng dữ liệu chỉ số điện.", HttpStatus.BAD_REQUEST),
    METER_READING_EXCEL_ROOM_REQUIRED(40919, "Meter reading Excel room required", "Dòng Excel %s đang thiếu mã phòng.", HttpStatus.BAD_REQUEST),
    METER_READING_EXCEL_VALUE_REQUIRED(40920, "Meter reading Excel value required", "Dòng Excel %s của phòng %s đang thiếu chỉ số điện mới.", HttpStatus.BAD_REQUEST),
    METER_READING_EXCEL_VALUE_INVALID(40921, "Meter reading Excel value invalid", "Dòng Excel %s của phòng %s có chỉ số điện mới không phải là số.", HttpStatus.BAD_REQUEST),
    METER_READING_EXCEL_VALUE_NEGATIVE(40922, "Meter reading Excel value negative", "Dòng Excel %s của phòng %s có chỉ số điện mới không được âm.", HttpStatus.BAD_REQUEST),
    METER_READING_EXCEL_ROLLOVER_COUNT_INVALID(40928, "Meter reading Excel rollover count invalid", "Dòng Excel %s của phòng %s có số lần quay vòng không hợp lệ.", HttpStatus.BAD_REQUEST),
    METER_READING_EXCEL_DUPLICATE_ROOM(40923, "Meter reading Excel duplicate room", "Phòng %s bị lặp tại dòng Excel %s. Mỗi phòng chỉ được xuất hiện một lần.", HttpStatus.BAD_REQUEST),
    METER_READING_EXCEL_ROOM_NOT_FOUND(40924, "Meter reading Excel room not found", "Không tìm thấy phòng %s trong hệ thống (dòng Excel %s).", HttpStatus.NOT_FOUND),
    METER_READING_EXCEL_ROOM_WRONG_PROPERTY(40925, "Meter reading Excel room wrong property", "Phòng %s không thuộc cơ sở của kỳ nhập (dòng Excel %s).", HttpStatus.BAD_REQUEST),
    METER_READING_EXCEL_ROOM_NOT_ELIGIBLE(40926, "Meter reading Excel room not eligible", "Phòng %s không có hợp đồng phát sinh trong kỳ %s (dòng Excel %s).", HttpStatus.BAD_REQUEST),

    // --- BILLING & PAYMENT (30xxx) ---
    TRANSFER_SETTLEMENT_NOT_FOUND(30101, "Transfer settlement not found", "Không tìm thấy quyết toán chuyển phòng", HttpStatus.NOT_FOUND),
    PAYMENT_INTENT_NOT_FOUND(30201, "Payment intent not found", "Không tìm thấy phiên thanh toán.", HttpStatus.NOT_FOUND),
    PAYMENT_INTENT_NOT_DEPOSIT(30202, "Payment intent is not a deposit", "Phiên thanh toán không thuộc đặt cọc phòng.", HttpStatus.BAD_REQUEST),
    EXTERNAL_SERVICE_ERROR(50201, "External service error", "Không thể xử lý yêu cầu với dịch vụ bên ngoài.", HttpStatus.BAD_GATEWAY),
    EXTERNAL_SERVICE_UNAVAILABLE(50301, "External service unavailable", "Dịch vụ bên ngoài hiện không khả dụng.", HttpStatus.SERVICE_UNAVAILABLE),

    // --- ROOM BOOKING & CONTRACT STATE ---
    ROOM_DEPOSIT_HOLD_ACTIVE(40411, "Room deposit hold active", "Phòng đang có người đặt cọc. Vui lòng chờ trong giây lát.", HttpStatus.CONFLICT),
    ROOM_DEPOSIT_LOCKED(40412, "Room deposit locked", "Phòng tạm khóa đặt cọc. Vui lòng thử lại sau.", HttpStatus.LOCKED),
    ROOM_DEPOSIT_UNAVAILABLE(40413, "Room deposit unavailable", "Phòng hiện không thể đặt cọc. Vui lòng chọn phòng khác.", HttpStatus.CONFLICT),
    ROOM_ALREADY_RESERVED(40414, "Room already reserved", "Phòng đã được đặt cọc. Vui lòng chọn phòng khác.", HttpStatus.CONFLICT),
    LEASE_RENEWAL_DATES_INVALID(40712, "Invalid lease renewal dates", "Ngày bắt đầu và ngày kết thúc gia hạn không hợp lệ.", HttpStatus.BAD_REQUEST),
    INVALID_REQUEST_STATE(10104, "Invalid request state", "Trạng thái yêu cầu không hợp lệ.", HttpStatus.UNPROCESSABLE_ENTITY),

    // --- NOTIFICATION (60xxx) ---
    NOTIFICATION_NOT_FOUND(60101, "Notification not found", "Không tìm thấy thông báo", HttpStatus.NOT_FOUND),
    NOTIFICATION_OUTBOX_NOT_FOUND(60102, "Notification outbox not found", "Không tìm thấy thông báo outbox", HttpStatus.NOT_FOUND),

    // --- BUSINESS VALIDATION ERRORS (700xx) ---
    MAINTENANCE_TICKET_ACCEPTANCE_STATUS_INVALID(70001, "MAINTENANCE_TICKET_ACCEPTANCE_STATUS_INVALID", "Chỉ tiếp nhận phiếu đang chờ tiếp nhận.", HttpStatus.BAD_REQUEST),
    MAINTENANCE_TICKET_REJECTION_STATUS_INVALID(70002, "MAINTENANCE_TICKET_REJECTION_STATUS_INVALID", "Chỉ từ chối phiếu đang chờ tiếp nhận.", HttpStatus.BAD_REQUEST),
    MAINTENANCE_TICKET_COMPLETION_STATUS_INVALID(70003, "MAINTENANCE_TICKET_COMPLETION_STATUS_INVALID", "Chỉ hoàn tất khi phiếu đang xử lý.", HttpStatus.BAD_REQUEST),
    MAINTENANCE_TICKET_CONFIRMATION_STATUS_INVALID(70004, "MAINTENANCE_TICKET_CONFIRMATION_STATUS_INVALID", "Chỉ xác nhận phiếu đang chờ xác nhận.", HttpStatus.BAD_REQUEST),
    MAINTENANCE_TICKET_NOT_FIXED_STATUS_INVALID(70005, "MAINTENANCE_TICKET_NOT_FIXED_STATUS_INVALID", "Chỉ báo chưa sửa xong khi phiếu đang chờ xác nhận.", HttpStatus.BAD_REQUEST),
    MAINTENANCE_TICKET_RATING_STATUS_INVALID(70006, "MAINTENANCE_TICKET_RATING_STATUS_INVALID", "Chỉ đánh giá phiếu đã hoàn tất.", HttpStatus.BAD_REQUEST),
    MAINTENANCE_TICKET_BEFORE_REPAIR_IMAGE_STATUS_INVALID(70007, "MAINTENANCE_TICKET_BEFORE_REPAIR_IMAGE_STATUS_INVALID", "Chỉ bổ sung ảnh trước sửa khi phiếu đang chờ tiếp nhận.", HttpStatus.BAD_REQUEST),
    BUSINESS_REQUEST_INVALID(70008, "BUSINESS_REQUEST_INVALID", "Yêu cầu không hợp lệ", HttpStatus.BAD_REQUEST),
    BILLING_EXCEL_PERIOD_REQUIRED(70009, "BILLING_EXCEL_PERIOD_REQUIRED", "Vui lòng chọn một kỳ tháng cụ thể để xuất Excel.", HttpStatus.BAD_REQUEST),
    BILLING_INVOICE_EXPORT_DATA_EMPTY(70010, "BILLING_INVOICE_EXPORT_DATA_EMPTY", "Chưa có hóa đơn để xuất", HttpStatus.BAD_REQUEST),
    BILLING_INVOICE_ROOM_EXPORT_DATA_EMPTY(70011, "BILLING_INVOICE_ROOM_EXPORT_DATA_EMPTY", "Không có hóa đơn gắn với phòng để xuất", HttpStatus.BAD_REQUEST),
    FAILED_EXPORT_EXCEL(70012, "FAILED_EXPORT_EXCEL", "Xuất file Excel thất bại", HttpStatus.INTERNAL_SERVER_ERROR),
    ROOM_PROMOTIONAL_PRICE_MUST_BE_BELOW_LIST_PRICE(70013, "ROOM_PROMOTIONAL_PRICE_MUST_BE_BELOW_LIST_PRICE", "Giá khuyến mãi phải thấp hơn giá niêm yết cơ bản của phòng.", HttpStatus.BAD_REQUEST),
    BILLING_INVOICE_LINE_NOT_FOUND(70014, "BILLING_INVOICE_LINE_NOT_FOUND", "Không tìm thấy dòng hóa đơn.", HttpStatus.NOT_FOUND),
    BILLING_INVOICE_LINE_NOT_IN_SELECTED_INVOICE(70015, "BILLING_INVOICE_LINE_NOT_IN_SELECTED_INVOICE", "Dòng hóa đơn không thuộc hóa đơn đã chọn.", HttpStatus.BAD_REQUEST),
    BILLING_UTILITY_INVOICE_COMPLAINT_UNSUPPORTED(70016, "BILLING_UTILITY_INVOICE_COMPLAINT_UNSUPPORTED", "Chỉ hỗ trợ khiếu nại hóa đơn điện nước.", HttpStatus.BAD_REQUEST),
    BILLING_UTILITY_INVOICE_MUST_BE_UNPAID_FOR_COMPLAINT(70017, "BILLING_UTILITY_INVOICE_MUST_BE_UNPAID_FOR_COMPLAINT", "Chỉ có thể khiếu nại hóa đơn điện nước chưa thanh toán.", HttpStatus.BAD_REQUEST),
    BILLING_UTILITY_INVOICE_LINE_TYPE_INVALID(70018, "BILLING_UTILITY_INVOICE_LINE_TYPE_INVALID", "Chỉ có thể khiếu nại dòng điện hoặc nước.", HttpStatus.BAD_REQUEST),
    BILLING_INVOICE_LINE_METER_READING_LINK_MISSING(70019, "BILLING_INVOICE_LINE_METER_READING_LINK_MISSING", "Dòng hóa đơn chưa liên kết chỉ số điện nước.", HttpStatus.BAD_REQUEST),
    BILLING_METER_READING_PROPOSAL_REQUIRED(70020, "BILLING_METER_READING_PROPOSAL_REQUIRED", "Vui lòng nhập chỉ số bạn cho là đúng.", HttpStatus.BAD_REQUEST),
    BILLING_METER_READING_PROPOSAL_BELOW_PREVIOUS(70021, "BILLING_METER_READING_PROPOSAL_BELOW_PREVIOUS", "Chỉ số đề xuất không được nhỏ hơn chỉ số cũ.", HttpStatus.BAD_REQUEST),
    BILLING_METER_READING_COMPLAINT_PENDING(70022, "BILLING_METER_READING_COMPLAINT_PENDING", "Chỉ số này đang có khiếu nại chờ xử lý.", HttpStatus.CONFLICT),
    BILLING_ACCOUNT_NOT_FOUND(70023, "BILLING_ACCOUNT_NOT_FOUND", "Không tìm thấy tài khoản.", HttpStatus.UNAUTHORIZED),
    BILLING_EVIDENCE_FILE_NOT_FOUND(70024, "BILLING_EVIDENCE_FILE_NOT_FOUND", "Không tìm thấy tệp minh chứng.", HttpStatus.NOT_FOUND),
    BILLING_INVOICE_NOT_FOUND(70025, "BILLING_INVOICE_NOT_FOUND", "Không tìm thấy hóa đơn.", HttpStatus.NOT_FOUND),
    COMPLAINT_DATA_NOT_FOUND(70026, "COMPLAINT_DATA_NOT_FOUND", "Không thể lưu dữ liệu khiếu nại.", HttpStatus.INTERNAL_SERVER_ERROR),
    MAINTENANCE_PROPERTY_VIEW_FORBIDDEN(70027, "MAINTENANCE_PROPERTY_VIEW_FORBIDDEN", "Bạn không có quyền xem phiếu sự cố của cơ sở này.", HttpStatus.FORBIDDEN),
    TENANT_ONLY_OPERATION(70028, "TENANT_ONLY_OPERATION", "Chỉ khách thuê mới được sử dụng chức năng này.", HttpStatus.FORBIDDEN),
    INTERNAL_EXPENSE_REPORT_VIEW_FORBIDDEN(70029, "INTERNAL_EXPENSE_REPORT_VIEW_FORBIDDEN", "Bạn không có quyền xem báo cáo chi phí nội bộ.", HttpStatus.FORBIDDEN),
    MAINTENANCE_ROOM_NOT_FOUND(70030, "MAINTENANCE_ROOM_NOT_FOUND", "Không tìm thấy phòng.", HttpStatus.BAD_REQUEST),
    MAINTENANCE_PROPERTY_SELECTION_INVALID(70031, "MAINTENANCE_PROPERTY_SELECTION_INVALID", "Vui lòng chọn cơ sở hợp lệ.", HttpStatus.BAD_REQUEST),
    MAINTENANCE_CURRENT_IMAGE_LIMIT_EXCEEDED(70032, "MAINTENANCE_CURRENT_IMAGE_LIMIT_EXCEEDED", "Chỉ được upload tối đa 3 ảnh hiện trạng.", HttpStatus.BAD_REQUEST),
    MAINTENANCE_REJECTION_REASON_REQUIRED(70033, "MAINTENANCE_REJECTION_REASON_REQUIRED", "Vui lòng nhập lý do từ chối.", HttpStatus.BAD_REQUEST),
    MAINTENANCE_COMPLETED_TICKET_COST_EDIT_FORBIDDEN(70034, "MAINTENANCE_COMPLETED_TICKET_COST_EDIT_FORBIDDEN", "Chỉ chủ trọ được sửa chi phí của ticket đã hoàn tất.", HttpStatus.FORBIDDEN),
    MAINTENANCE_REPAIR_INFO_UPDATE_FORBIDDEN(70035, "MAINTENANCE_REPAIR_INFO_UPDATE_FORBIDDEN", "Không thể cập nhật thông tin xử lý ở trạng thái này.", HttpStatus.BAD_REQUEST),
    MAINTENANCE_ACTUAL_COST_NEGATIVE(70036, "MAINTENANCE_ACTUAL_COST_NEGATIVE", "Chi phí thực tế không được âm", HttpStatus.BAD_REQUEST),
    MAINTENANCE_RATING_OUT_OF_RANGE(70037, "MAINTENANCE_RATING_OUT_OF_RANGE", "Đánh giá phải từ 1 đến 5 sao.", HttpStatus.BAD_REQUEST),
    MAINTENANCE_TICKET_ALREADY_RATED(70038, "MAINTENANCE_TICKET_ALREADY_RATED", "Bạn đã đánh giá phiếu này.", HttpStatus.BAD_REQUEST),
    MAINTENANCE_UPLOAD_IMAGE_REQUIRED(70039, "MAINTENANCE_UPLOAD_IMAGE_REQUIRED", "Vui lòng chọn ảnh cần upload.", HttpStatus.BAD_REQUEST),
    MAINTENANCE_TENANT_BEFORE_REPAIR_IMAGE_ONLY(70040, "MAINTENANCE_TENANT_BEFORE_REPAIR_IMAGE_ONLY", "Khách thuê chỉ được upload ảnh trước sửa.", HttpStatus.FORBIDDEN),
    MAINTENANCE_ROOM_TICKET_VIEW_FORBIDDEN(70041, "MAINTENANCE_ROOM_TICKET_VIEW_FORBIDDEN", "Bạn không có quyền xem ticket của phòng này.", HttpStatus.FORBIDDEN),
    MAINTENANCE_TENANT_ROOM_NOT_RESOLVED(70042, "MAINTENANCE_TENANT_ROOM_NOT_RESOLVED", "Không xác định được phòng đang thuê để tạo phiếu sự cố.", HttpStatus.BAD_REQUEST),
    MAINTENANCE_TENANT_ROOM_TICKET_ONLY(70043, "MAINTENANCE_TENANT_ROOM_TICKET_ONLY", "Khách thuê chỉ được tạo phiếu sự cố phòng đang thuê.", HttpStatus.FORBIDDEN),
    MAINTENANCE_ROOM_TICKET_CREATE_FORBIDDEN(70044, "MAINTENANCE_ROOM_TICKET_CREATE_FORBIDDEN", "Bạn không có quyền tạo phiếu sự cố cho phòng này.", HttpStatus.FORBIDDEN),
    MAINTENANCE_BEFORE_REPAIR_IMAGE_LIMIT_EXCEEDED(70045, "MAINTENANCE_BEFORE_REPAIR_IMAGE_LIMIT_EXCEEDED", "Chỉ được upload tối đa 3 ảnh trước sửa.", HttpStatus.BAD_REQUEST),
    MAINTENANCE_COMMON_AREA_PROPERTY_REQUIRED(70046, "MAINTENANCE_COMMON_AREA_PROPERTY_REQUIRED", "Vui lòng chọn cơ sở/property cho sự cố khu vực chung.", HttpStatus.BAD_REQUEST),
    MAINTENANCE_PROPERTY_NOT_FOUND(70047, "MAINTENANCE_PROPERTY_NOT_FOUND", "Không tìm thấy cơ sở/property.", HttpStatus.BAD_REQUEST),
    MAINTENANCE_ROOM_ID_REQUIRED(70048, "MAINTENANCE_ROOM_ID_REQUIRED", "Ticket phòng cần có roomId.", HttpStatus.BAD_REQUEST),
    MAINTENANCE_PAID_EXPENSE_AMOUNT_IMMUTABLE(70049, "MAINTENANCE_PAID_EXPENSE_AMOUNT_IMMUTABLE", "Khoản chi sự cố đã thanh toán, không thể đổi số tiền.", HttpStatus.CONFLICT),
    MAINTENANCE_PAID_EXPENSE_PAYER_IMMUTABLE(70050, "MAINTENANCE_PAID_EXPENSE_PAYER_IMMUTABLE", "Khoản chi sự cố đã thanh toán, không thể chuyển người chịu phí.", HttpStatus.CONFLICT),
    MAINTENANCE_EXPENSE_RECEIPT_NOT_FOUND(70051, "MAINTENANCE_EXPENSE_RECEIPT_NOT_FOUND", "Không tìm thấy chứng từ chi phí.", HttpStatus.BAD_REQUEST),
    MAINTENANCE_DRAFT_INVOICE_REQUIRED(70052, "MAINTENANCE_DRAFT_INVOICE_REQUIRED", "Phiếu chưa có hóa đơn nháp để phát hành.", HttpStatus.BAD_REQUEST),
    MAINTENANCE_COMPENSATION_COST_MUST_BE_POSITIVE(70053, "MAINTENANCE_COMPENSATION_COST_MUST_BE_POSITIVE", "Chi phí bồi thường phải lớn hơn 0.", HttpStatus.BAD_REQUEST),
    MAINTENANCE_ROOM_NOT_FOUND_FOR_TENANT_CHARGE(70054, "MAINTENANCE_ROOM_NOT_FOUND_FOR_TENANT_CHARGE", "Không tìm thấy phòng để lên lịch thu khách.", HttpStatus.BAD_REQUEST),
    MAINTENANCE_ROOM_NOT_FOUND_FOR_INVOICE(70055, "MAINTENANCE_ROOM_NOT_FOUND_FOR_INVOICE", "Không tìm thấy phòng để xuất hóa đơn.", HttpStatus.BAD_REQUEST),
    MAINTENANCE_TICKET_CONTRACT_NOT_FOUND(70056, "MAINTENANCE_TICKET_CONTRACT_NOT_FOUND", "Không tìm thấy hợp đồng của phiếu sự cố.", HttpStatus.BAD_REQUEST),
    MAINTENANCE_COMMON_AREA_INVOICE_UNSUPPORTED(70057, "MAINTENANCE_COMMON_AREA_INVOICE_UNSUPPORTED", "Phiếu khu vực chung không thể xuất hóa đơn cho khách.", HttpStatus.BAD_REQUEST),
    MAINTENANCE_ACTIVE_CONTRACT_REQUIRED_FOR_INVOICE(70058, "MAINTENANCE_ACTIVE_CONTRACT_REQUIRED_FOR_INVOICE", "Phòng chưa có hợp đồng đang hiệu lực, không thể xuất hóa đơn cho khách.", HttpStatus.BAD_REQUEST),
    MAINTENANCE_TICKET_NOT_FOUND(70059, "MAINTENANCE_TICKET_NOT_FOUND", "Không tìm thấy phiếu sự cố.", HttpStatus.NOT_FOUND),
    MAINTENANCE_PROPERTY_PROCESSING_FORBIDDEN(70060, "MAINTENANCE_PROPERTY_PROCESSING_FORBIDDEN", "Bạn không có quyền xử lý phiếu sự cố của cơ sở này.", HttpStatus.FORBIDDEN),
    MAINTENANCE_TICKET_VIEW_FORBIDDEN(70061, "MAINTENANCE_TICKET_VIEW_FORBIDDEN", "Bạn không có quyền xem phiếu sự cố này.", HttpStatus.FORBIDDEN),
    VALID_TENANT_REQUIRED(70062, "VALID_TENANT_REQUIRED", "Chỉ khách thuê hợp lệ được thực hiện thao tác này.", HttpStatus.FORBIDDEN),
    MAINTENANCE_COMMON_AREA_TENANT_CONFIRMATION_FORBIDDEN(70063, "MAINTENANCE_COMMON_AREA_TENANT_CONFIRMATION_FORBIDDEN", "Khách thuê không được xác nhận phiếu khu vực chung.", HttpStatus.FORBIDDEN),
    MAINTENANCE_TICKET_PROCESSING_FORBIDDEN(70064, "MAINTENANCE_TICKET_PROCESSING_FORBIDDEN", "Bạn không có quyền xử lý phiếu sự cố.", HttpStatus.FORBIDDEN),
    AUTHENTICATION_SESSION_INVALID(70065, "AUTHENTICATION_SESSION_INVALID", "Phiên đăng nhập không hợp lệ.", HttpStatus.UNAUTHORIZED),
    MAINTENANCE_TICKET_DATA_INVALID(70066, "MAINTENANCE_TICKET_DATA_INVALID", "Dữ liệu tạo phiếu không hợp lệ.", HttpStatus.BAD_REQUEST),
    MAINTENANCE_DESCRIPTION_TOO_SHORT(70067, "MAINTENANCE_DESCRIPTION_TOO_SHORT", "Mô tả sự cố phải có tối thiểu 10 ký tự.", HttpStatus.BAD_REQUEST),
    MAINTENANCE_ATTACHMENT_NOT_FOUND(70068, "MAINTENANCE_ATTACHMENT_NOT_FOUND", "Một hoặc nhiều file không tồn tại.", HttpStatus.BAD_REQUEST),
    MAINTENANCE_IMAGE_FORMAT_UNSUPPORTED(70069, "MAINTENANCE_IMAGE_FORMAT_UNSUPPORTED", "MVP chỉ hỗ trợ ảnh jpg, jpeg, png, webp.", HttpStatus.BAD_REQUEST),
    MAINTENANCE_STATUS_TRANSITION_INVALID(70070, "MAINTENANCE_STATUS_TRANSITION_INVALID", "Không thể chuyển trạng thái phiếu sự cố.", HttpStatus.BAD_REQUEST),
    MAINTENANCE_TICKET_STATUS_INVALID(70071, "MAINTENANCE_TICKET_STATUS_INVALID", "Trạng thái phiếu sự cố không hợp lệ.", HttpStatus.BAD_REQUEST),
    MAINTENANCE_SCOPE_INVALID(70072, "MAINTENANCE_SCOPE_INVALID", "Phạm vi sự cố không hợp lệ.", HttpStatus.BAD_REQUEST),
    LEASE_CONTRACT_NOT_FOUND(70073, "LEASE_CONTRACT_NOT_FOUND", "Không tìm thấy hợp đồng thuê.", HttpStatus.NOT_FOUND),
    LEASE_ACTIVE_SIGNED_FILE_REPLACEMENT_FORBIDDEN(70074, "LEASE_ACTIVE_SIGNED_FILE_REPLACEMENT_FORBIDDEN", "Hợp đồng đã ACTIVE, không thể upload thay file trong luồng này.", HttpStatus.BAD_REQUEST),
    LEASE_SIGNED_FILE_ALREADY_EXISTS(70075, "LEASE_SIGNED_FILE_ALREADY_EXISTS", "Hợp đồng thuê đã có file đã ký. Gửi replace=true nếu muốn thay thế.", HttpStatus.CONFLICT),
    LEASE_SIGNED_FILE_SAVE_FAILED(70076, "LEASE_SIGNED_FILE_SAVE_FAILED", "Không lưu được file hợp đồng.", HttpStatus.INTERNAL_SERVER_ERROR),
    LEASE_CONTRACT_NOT_FOUND_FOR_LIQUIDATION(70077, "LEASE_CONTRACT_NOT_FOUND_FOR_LIQUIDATION", "Không tìm thấy hợp đồng thuê.", HttpStatus.NOT_FOUND),
    LEASE_ALREADY_LIQUIDATED(70078, "LEASE_ALREADY_LIQUIDATED", "Hợp đồng đã được thanh lý.", HttpStatus.BAD_REQUEST),
    LEASE_LIQUIDATION_STATUS_INVALID(70079, "LEASE_LIQUIDATION_STATUS_INVALID", "Chỉ thanh lý hợp đồng đang hiệu lực, sắp hết hạn, hết hạn hoặc chờ thanh lý.", HttpStatus.BAD_REQUEST),
    LEASE_SIGNED_FILE_NAME_MISMATCH(70080, "LEASE_SIGNED_FILE_NAME_MISMATCH", "Tên file hợp đồng đã ký phải khớp mã hợp đồng %s (không tính phần mở rộng).", HttpStatus.BAD_REQUEST),
    LEASE_ROOM_REQUIRED(70080, "LEASE_ROOM_REQUIRED", "Hợp đồng chưa gắn phòng.", HttpStatus.BAD_REQUEST),
    LEASE_LIQUIDATION_RECORD_REQUIRED(70081, "LEASE_LIQUIDATION_RECORD_REQUIRED", "Vui lòng lập hồ sơ thanh lý trước khi hoàn tất.", HttpStatus.BAD_REQUEST),
    LEASE_REPLACEMENT_CONTRACT_REQUIRED_FOR_REMAINING_OCCUPANTS(70082, "LEASE_REPLACEMENT_CONTRACT_REQUIRED_FOR_REMAINING_OCCUPANTS", "Vui lòng lập hợp đồng thay thế cho người ở lại trước khi hoàn tất thanh lý.", HttpStatus.CONFLICT),
    LEASE_LIQUIDATION_ALREADY_COMPLETED(70083, "LEASE_LIQUIDATION_ALREADY_COMPLETED", "Hợp đồng đã được thanh lý.", HttpStatus.BAD_REQUEST),
    LEASE_LIQUIDATION_PROCESSING_STATUS_INVALID(70084, "LEASE_LIQUIDATION_PROCESSING_STATUS_INVALID", "Chỉ xử lý thanh lý cho hợp đồng đang hiệu lực, sắp hết hạn, hết hạn hoặc chờ thanh lý.", HttpStatus.BAD_REQUEST),
    LEASE_LIQUIDATION_ALREADY_CONFIRMED(70085, "LEASE_LIQUIDATION_ALREADY_CONFIRMED", "Hồ sơ thanh lý đã được xác nhận.", HttpStatus.BAD_REQUEST),
    LEASE_PRIMARY_HOLDER_REQUIRED(70086, "LEASE_PRIMARY_HOLDER_REQUIRED", "Hợp đồng phải có người ký chính.", HttpStatus.BAD_REQUEST),
    LEASE_REPLACEMENT_HOLDER_REQUIRED(70087, "LEASE_REPLACEMENT_HOLDER_REQUIRED", "Người đứng tên mới là bắt buộc.", HttpStatus.BAD_REQUEST),
    LEASE_ACTIVE_OCCUPANTS_REQUIRED(70088, "LEASE_ACTIVE_OCCUPANTS_REQUIRED", "Hợp đồng không có người ở đang hoạt động.", HttpStatus.CONFLICT),
    LEASE_HOLDER_REPLACEMENT_DATA_REQUIRED(70089, "LEASE_HOLDER_REPLACEMENT_DATA_REQUIRED", "Dữ liệu thay người đứng tên là bắt buộc.", HttpStatus.BAD_REQUEST),
    LEASE_ROOM_ACTIVE_CONTRACT_CONFLICT(70090, "LEASE_ROOM_ACTIVE_CONTRACT_CONFLICT", "Phòng đã có một hợp đồng khác đang hiệu lực.", HttpStatus.CONFLICT),
    LEASE_REPLACEMENT_CONTRACT_UNUSABLE(70091, "LEASE_REPLACEMENT_CONTRACT_UNUSABLE", "Hợp đồng thay thế không thể sử dụng.", HttpStatus.CONFLICT),
    LEASE_REPLACEMENT_CONTRACT_ROOM_IMMUTABLE(70092, "LEASE_REPLACEMENT_CONTRACT_ROOM_IMMUTABLE", "Hợp đồng thay thế phải giữ nguyên phòng.", HttpStatus.CONFLICT),
    LEASE_REPLACEMENT_HOLDER_MISMATCH(70093, "LEASE_REPLACEMENT_HOLDER_MISMATCH", "Người ký chính của hợp đồng thay thế không khớp với yêu cầu.", HttpStatus.CONFLICT),
    LEASE_REPLACEMENT_CONTRACT_MUST_BE_SIGNED(70094, "LEASE_REPLACEMENT_CONTRACT_MUST_BE_SIGNED", "Hợp đồng thay thế phải được ký trước khi thanh lý.", HttpStatus.CONFLICT),
    LEASE_REPLACEMENT_CONTRACT_STATUS_INVALID(70095, "LEASE_REPLACEMENT_CONTRACT_STATUS_INVALID", "Trạng thái hợp đồng thay thế không hợp lệ để kích hoạt.", HttpStatus.CONFLICT),
    LEASE_OCCUPANT_NOT_ACTIVE(70096, "LEASE_OCCUPANT_NOT_ACTIVE", "Người ở không còn hoạt động trong hợp đồng.", HttpStatus.BAD_REQUEST),
    LEASE_CONTRACT_NOT_FOUND_FOR_HANDOVER(70097, "LEASE_CONTRACT_NOT_FOUND_FOR_HANDOVER", "Không tìm thấy hợp đồng thuê.", HttpStatus.NOT_FOUND),
    LEASE_ALREADY_LIQUIDATED_FOR_HANDOVER(70098, "LEASE_ALREADY_LIQUIDATED_FOR_HANDOVER", "Hợp đồng đã được thanh lý.", HttpStatus.BAD_REQUEST),
    LEASE_LIQUIDATION_NOT_ALLOWED(70099, "LEASE_LIQUIDATION_NOT_ALLOWED", "Hợp đồng chưa thể lập hồ sơ thanh lý.", HttpStatus.BAD_REQUEST),
    LEASE_LIQUIDATION_ALREADY_CONFIRMED_FOR_HANDOVER(70100, "LEASE_LIQUIDATION_ALREADY_CONFIRMED_FOR_HANDOVER", "Hồ sơ thanh lý đã được xác nhận.", HttpStatus.BAD_REQUEST),
    LEASE_LIQUIDATION_INVOICE_PAID_IMMUTABLE(70101, "LEASE_LIQUIDATION_INVOICE_PAID_IMMUTABLE", "Không thể cập nhật hóa đơn thanh lý đã có thanh toán.", HttpStatus.CONFLICT),
    LEASE_OUTSTANDING_INVOICES_MUST_BE_PAID(70102, "LEASE_OUTSTANDING_INVOICES_MUST_BE_PAID", "Khách thuê cần thanh toán hết hóa đơn còn nợ trước khi hoàn tất thanh lý.", HttpStatus.CONFLICT),
    LEASE_DEPOSIT_SETTLEMENT_CONFIRMATION_REQUIRED(70103, "LEASE_DEPOSIT_SETTLEMENT_CONFIRMATION_REQUIRED", "Vui lòng hoàn tất hoàn cọc và chờ khách thuê xác nhận đã nhận tiền trước khi thanh lý hợp đồng.", HttpStatus.CONFLICT),
    LEASE_MOVE_OUT_HANDOVER_REQUIRED(70104, "LEASE_MOVE_OUT_HANDOVER_REQUIRED", "Vui lòng hoàn tất bàn giao trả phòng trước khi thanh lý hợp đồng.", HttpStatus.CONFLICT),
    LEASE_HANDOVER_METER_READING_BELOW_PREVIOUS(70105, "LEASE_HANDOVER_METER_READING_BELOW_PREVIOUS", "Chỉ số mới không được nhỏ hơn chỉ số cũ.", HttpStatus.BAD_REQUEST),
    LEASE_RENEWAL_STATUS_INVALID(70106, "LEASE_RENEWAL_STATUS_INVALID", "Chỉ được tái ký hợp đồng ACTIVE, EXPIRING_SOON hoặc EXPIRED.", HttpStatus.BAD_REQUEST),
    LEASE_RENEWAL_ALREADY_EXISTS(70107, "LEASE_RENEWAL_ALREADY_EXISTS", "Hợp đồng này đã có hợp đồng tái ký.", HttpStatus.CONFLICT),
    LEASE_RENEWAL_ROOM_REQUIRED(70108, "LEASE_RENEWAL_ROOM_REQUIRED", "Hợp đồng chưa gắn phòng.", HttpStatus.BAD_REQUEST),
    LEASE_RENEWAL_ROOM_CONTRACT_CONFLICT(70109, "LEASE_RENEWAL_ROOM_CONTRACT_CONFLICT", "Phòng đang có hợp đồng hiệu lực khác.", HttpStatus.CONFLICT),
    LEASE_CO_OCCUPANT_ADD_FORBIDDEN(70110, "LEASE_CO_OCCUPANT_ADD_FORBIDDEN", "Hợp đồng không thể thêm người ở cùng.", HttpStatus.BAD_REQUEST),
    LEASE_CO_OCCUPANT_PROFILE_REQUIRED(70111, "LEASE_CO_OCCUPANT_PROFILE_REQUIRED", "Hồ sơ người ở cùng là bắt buộc.", HttpStatus.BAD_REQUEST),
    LEASE_PERSON_ALREADY_PRIMARY_HOLDER(70112, "LEASE_PERSON_ALREADY_PRIMARY_HOLDER", "Người này đã là người đứng tên hợp đồng.", HttpStatus.CONFLICT),
    LEASE_CO_OCCUPANT_PROFILE_NOT_FOUND(70113, "LEASE_CO_OCCUPANT_PROFILE_NOT_FOUND", "Không tìm thấy hồ sơ người ở cùng.", HttpStatus.NOT_FOUND),
    LEASE_OCCUPANCY_LIMIT_REACHED(70114, "LEASE_OCCUPANCY_LIMIT_REACHED", "Phòng đã đạt số người ở tối đa.", HttpStatus.CONFLICT),
    LEASE_INTENT_STATUS_INVALID(70115, "LEASE_INTENT_STATUS_INVALID", "Chỉ ghi nhận ý định cho hợp đồng ACTIVE hoặc EXPIRING_SOON.", HttpStatus.BAD_REQUEST),
    LEASE_TENANT_INTENT_INVALID(70116, "LEASE_TENANT_INTENT_INVALID", "Ý định khách không hợp lệ.", HttpStatus.BAD_REQUEST),
    LEASE_MOVE_OUT_TRANSFER_WINDOW_INVALID(70117, "LEASE_MOVE_OUT_TRANSFER_WINDOW_INVALID", "Chỉ ghi nhận MOVE_OUT/TRANSFER khi hợp đồng còn 3 tháng trở xuống.", HttpStatus.UNPROCESSABLE_ENTITY),
    LEASE_EXPECTED_HANDOVER_DATE_REQUIRED(70118, "LEASE_EXPECTED_HANDOVER_DATE_REQUIRED", "Cần có ngày dự kiến bàn giao phòng.", HttpStatus.UNPROCESSABLE_ENTITY),
    LEASE_EXPECTED_HANDOVER_DATE_IN_PAST(70119, "LEASE_EXPECTED_HANDOVER_DATE_IN_PAST", "Ngày dự kiến bàn giao không được trước hôm nay.", HttpStatus.UNPROCESSABLE_ENTITY),
    LEASE_EXPECTED_HANDOVER_DATE_AFTER_CONTRACT_END(70120, "LEASE_EXPECTED_HANDOVER_DATE_AFTER_CONTRACT_END", "Ngày dự kiến bàn giao không được sau ngày kết thúc hợp đồng.", HttpStatus.UNPROCESSABLE_ENTITY),
    LEASE_PRIMARY_HOLDER_ONLY_INTENT(70121, "LEASE_PRIMARY_HOLDER_ONLY_INTENT", "Chỉ người ký chính của hợp đồng mới được ghi nhận ý định.", HttpStatus.FORBIDDEN),
    LEASE_ACTIVATION_STATUS_INVALID(70122, "LEASE_ACTIVATION_STATUS_INVALID", "Chỉ được kích hoạt hợp đồng đang chờ ký.", HttpStatus.BAD_REQUEST),
    LEASE_SIGNED_FILE_REQUIRED_FOR_ACTIVATION(70123, "LEASE_SIGNED_FILE_REQUIRED_FOR_ACTIVATION", "Cần upload file hợp đồng đã ký trước khi kích hoạt.", HttpStatus.BAD_REQUEST),
    LEASE_ACTIVATION_PRIMARY_HOLDER_REQUIRED(70124, "LEASE_ACTIVATION_PRIMARY_HOLDER_REQUIRED", "Hợp đồng chưa có người ký chính.", HttpStatus.BAD_REQUEST),
    LEASE_CONTRACT_DATES_INVALID(70125, "LEASE_CONTRACT_DATES_INVALID", "Ngày bắt đầu/kết thúc hợp đồng không hợp lệ.", HttpStatus.BAD_REQUEST),
    LEASE_ACTIVATION_HANDOVER_REQUIRED(70126, "LEASE_ACTIVATION_HANDOVER_REQUIRED", "Cần hoàn thành bàn giao phòng, nhập số điện và upload biên bản bàn giao đã ký trước khi kích hoạt hợp đồng.", HttpStatus.BAD_REQUEST),
    LEASE_ROOM_STATUS_INVALID_FOR_ACTIVATION(70127, "LEASE_ROOM_STATUS_INVALID_FOR_ACTIVATION", "Phòng phải ở trạng thái trống hoặc đã đặt cọc trước khi kích hoạt hợp đồng.", HttpStatus.BAD_REQUEST),
    LEASE_ROOM_ACTIVE_CONTRACT_EXISTS(70128, "LEASE_ROOM_ACTIVE_CONTRACT_EXISTS", "Phòng đã có hợp đồng đang hiệu lực.", HttpStatus.BAD_REQUEST),
    LEASE_REPLACEMENT_LIQUIDATION_REQUIRED(70129, "LEASE_REPLACEMENT_LIQUIDATION_REQUIRED", "Vui lòng hoàn tất quy trình thanh lý để kích hoạt hợp đồng thay thế.", HttpStatus.CONFLICT),
    LEASE_PREVIOUS_CONTRACT_RENEWAL_STATUS_INVALID(70130, "LEASE_PREVIOUS_CONTRACT_RENEWAL_STATUS_INVALID", "Hợp đồng trước không còn ở trạng thái cho phép kích hoạt gia hạn.", HttpStatus.BAD_REQUEST),
    LEASE_ENDED_CONTRACT_IMMUTABLE(70131, "LEASE_ENDED_CONTRACT_IMMUTABLE", "Không thể cập nhật thời hạn của hợp đồng đã kết thúc.", HttpStatus.BAD_REQUEST),
    LEASE_CONTRACT_ROOM_REQUIRED(70132, "LEASE_CONTRACT_ROOM_REQUIRED", "Hợp đồng phải gắn với phòng.", HttpStatus.BAD_REQUEST),
    CONTRACT_MUST_HAVE_HOLDER(70133, "CONTRACT_MUST_HAVE_HOLDER", "Hợp đồng phải có người ký chính.", HttpStatus.BAD_REQUEST),
    LEASE_CONTRACT_DATES_RANGE_INVALID(70134, "LEASE_CONTRACT_DATES_RANGE_INVALID", "Ngày bắt đầu và ngày kết thúc hợp đồng không hợp lệ.", HttpStatus.BAD_REQUEST),
    LEASE_PAYMENT_CYCLE_INVALID(70135, "LEASE_PAYMENT_CYCLE_INVALID", "Chu kỳ thanh toán chỉ được là 1 hoặc 3 tháng.", HttpStatus.BAD_REQUEST),
    LEASE_RENT_AMOUNT_INVALID(70136, "LEASE_RENT_AMOUNT_INVALID", "Giá thuê hàng tháng phải lớn hơn 0.", HttpStatus.BAD_REQUEST),
    INVALID_DEPOSIT_AMOUNT(70137, "INVALID_DEPOSIT_AMOUNT", "Tiền cọc không hợp lệ.", HttpStatus.BAD_REQUEST),
    LEASE_ROOM_STATUS_INVALID_FOR_CREATION(70138, "LEASE_ROOM_STATUS_INVALID_FOR_CREATION", "Chỉ được tạo hợp đồng cho phòng trống, sắp trống hoặc phòng đã đặt cọc.", HttpStatus.BAD_REQUEST),
    LEASE_OCCUPANCY_LIMIT_EXCEEDED(70139, "LEASE_OCCUPANCY_LIMIT_EXCEEDED", "Số người ở vượt quá số người tối đa của phòng.", HttpStatus.BAD_REQUEST),
    LEASE_EXPECTED_VACANCY_DATE_REQUIRED(70140, "LEASE_EXPECTED_VACANCY_DATE_REQUIRED", "Phòng sắp trống chưa có ngày dự kiến bàn giao.", HttpStatus.CONFLICT),
    LEASE_EXPECTED_MOVE_IN_DATE_INVALID(70141, "LEASE_EXPECTED_MOVE_IN_DATE_INVALID", "Ngày dự kiến vào ở phải sau hoặc bằng ngày phòng dự kiến trống.", HttpStatus.UNPROCESSABLE_ENTITY),
    LEASE_START_DATE_REQUIRED(70142, "LEASE_START_DATE_REQUIRED", "Ngày bắt đầu hợp đồng là bắt buộc.", HttpStatus.BAD_REQUEST),
    DEPOSIT_AMOUNT_MUST_GREATER_THAN_ZERO(70143, "DEPOSIT_AMOUNT_MUST_GREATER_THAN_ZERO", "Tiền cọc phải lớn hơn hoặc bằng 0.", HttpStatus.BAD_REQUEST),
    LEASE_OCCUPANTS_INCOMPLETE(70144, "LEASE_OCCUPANTS_INCOMPLETE", "Hợp đồng chưa đủ thông tin người ở.", HttpStatus.BAD_REQUEST),
    NEW_CONTRACT_CODE_OVERFLOWS(70145, "NEW_CONTRACT_CODE_OVERFLOWS", "Mã hợp đồng mới không được vượt quá 80 ký tự.", HttpStatus.BAD_REQUEST),
    NEW_CONTRACT_CODE_EXISTED(70146, "NEW_CONTRACT_CODE_EXISTED", "Mã hợp đồng mới đã tồn tại.", HttpStatus.CONFLICT),
    LEASE_ROOM_PREBOOKED_BY_OTHER_TENANT(70147, "LEASE_ROOM_PREBOOKED_BY_OTHER_TENANT", "Phòng đang được đặt trước cho người khác. Vui lòng thử lại sau.", HttpStatus.CONFLICT),
    LEASE_RENEWAL_ROOM_RESERVED_BY_OTHER_TENANT(70148, "LEASE_RENEWAL_ROOM_RESERVED_BY_OTHER_TENANT", "Phòng đã có khách khác đặt cọc/giữ chỗ, không thể gia hạn. Vui lòng liên hệ quản lý.", HttpStatus.CONFLICT),
    LEASE_RENEWAL_CONFIRMATION_FORBIDDEN(70149, "LEASE_RENEWAL_CONFIRMATION_FORBIDDEN", "Chỉ chủ trọ hoặc quản lý mới có quyền xác nhận tái ký hợp đồng.", HttpStatus.FORBIDDEN),
    LEASE_ACTIVATION_INITIAL_RENT_PAYMENT_REQUIRED(70162, "LEASE_ACTIVATION_INITIAL_RENT_PAYMENT_REQUIRED", "Cần xác nhận đã thu tiền phòng kỳ đầu trước khi kích hoạt hợp đồng.", HttpStatus.BAD_REQUEST),
    LEASE_ACTIVATION_INITIAL_RENT_PAYMENT_INVALID(70163, "LEASE_ACTIVATION_INITIAL_RENT_PAYMENT_INVALID", "Tiền phòng kỳ đầu phải đúng bằng %s VNĐ.", HttpStatus.BAD_REQUEST),
    LEASE_PAYMENT_CYCLE_UPDATE_NOT_ALLOWED(70164, "LEASE_PAYMENT_CYCLE_UPDATE_NOT_ALLOWED", "Chỉ được thay đổi chu kỳ thanh toán khi hợp đồng còn nháp/chờ ký, chưa ký và chưa phát sinh hóa đơn.", HttpStatus.CONFLICT),
    LEASE_SIGNED_TERMS_UPDATE_NOT_ALLOWED(70165, "LEASE_SIGNED_TERMS_UPDATE_NOT_ALLOWED", "Điều khoản tài chính của hợp đồng đã ký chỉ được điều chỉnh bởi chủ trọ hoặc sau khi yêu cầu được chủ trọ phê duyệt.", HttpStatus.CONFLICT),
    LEASE_CONTRACT_DATES_UPDATE_NOT_ALLOWED(70166, "LEASE_CONTRACT_DATES_UPDATE_NOT_ALLOWED", "Ngày bắt đầu và ngày kết thúc chỉ được chỉnh sửa trước khi hợp đồng được ký.", HttpStatus.CONFLICT),
    LEASE_PAYMENT_CYCLE_TERM_INVALID(70167, "LEASE_PAYMENT_CYCLE_TERM_INVALID", "Thời hạn còn lại của hợp đồng phải là bội số của chu kỳ thanh toán.", HttpStatus.BAD_REQUEST),
    LEASE_TRANSFER_WORKFLOW_REQUIRED(70150, "LEASE_TRANSFER_WORKFLOW_REQUIRED", "Hợp đồng thuộc yêu cầu chuyển phòng; vui lòng xử lý bàn giao/kích hoạt trong luồng chuyển phòng.", HttpStatus.BAD_REQUEST),
    LEASE_SIGNED_HANDOVER_DOCUMENT_NOT_FOUND(70151, "LEASE_SIGNED_HANDOVER_DOCUMENT_NOT_FOUND", "Chưa có biên bản bàn giao đã ký.", HttpStatus.NOT_FOUND),
    SIGNED_HANDOVER_CONTRACT_NOT_FOUND(70152, "SIGNED_HANDOVER_CONTRACT_NOT_FOUND", "Không tìm thấy biên bản bàn giao đã ký.", HttpStatus.NOT_FOUND),
    LEASE_SIGNED_CONTRACT_NOT_FOUND(70153, "LEASE_SIGNED_CONTRACT_NOT_FOUND", "Chưa có bản hợp đồng thuê đã ký.", HttpStatus.NOT_FOUND),
    SIGNED_CONTRACT_FILE_NOT_FOUND(70154, "SIGNED_CONTRACT_FILE_NOT_FOUND", "Không tìm thấy file hợp đồng thuê đã ký.", HttpStatus.NOT_FOUND),
    AUTHENTICATION_REQUIRED(70155, "AUTHENTICATION_REQUIRED", "Chưa đăng nhập.", HttpStatus.UNAUTHORIZED),
    LEASE_CO_OCCUPANT_ACCESS_DENIED(70156, "LEASE_CO_OCCUPANT_ACCESS_DENIED", "Bạn không phải người ở cùng của hợp đồng này.", HttpStatus.FORBIDDEN),
    LEASE_CO_OCCUPANT_INTENT_INVALID(70157, "LEASE_CO_OCCUPANT_INTENT_INVALID", "Ý định người ở cùng không hợp lệ.", HttpStatus.BAD_REQUEST),
    MAINTENANCE_REPAIR_PLAN_REQUIRED(70158, "MAINTENANCE_REPAIR_PLAN_REQUIRED", "Vui lòng nhập người sửa, hạng mục và chi phí trước khi gửi phương án cho khách thuê.", HttpStatus.BAD_REQUEST),
    MAINTENANCE_TENANT_DECISION_STATUS_INVALID(70159, "MAINTENANCE_TENANT_DECISION_STATUS_INVALID", "Chỉ được quyết định sửa chữa khi phiếu đang chờ khách thuê quyết định.", HttpStatus.BAD_REQUEST),
    MAINTENANCE_REPAIR_DECLINE_REASON_REQUIRED(70160, "MAINTENANCE_REPAIR_DECLINE_REASON_REQUIRED", "Vui lòng nhập lý do khi không đồng ý sửa chữa.", HttpStatus.BAD_REQUEST),
    MAINTENANCE_REPAIR_CONSENT_REQUIRED(70161, "MAINTENANCE_REPAIR_CONSENT_REQUIRED", "Chỉ được bắt đầu xử lý sau khi khách thuê đã đồng ý sửa chữa.", HttpStatus.BAD_REQUEST),

    // --- INTERNAL TECHNICAL ERRORS ---
    REQUEST_CODE_ALLOCATION_FAILED(50001, "Request code allocation failed", "Không thể tạo mã yêu cầu. Vui lòng thử lại.", HttpStatus.INTERNAL_SERVER_ERROR),
    INVALID_PASSWORD_LENGTH(50002, "Invalid password length", "Độ dài mật khẩu không hợp lệ.", HttpStatus.BAD_REQUEST),
    HMAC_SECRET_INVALID(50003, "HMAC secret invalid", "Cấu hình khóa bảo mật không hợp lệ.", HttpStatus.INTERNAL_SERVER_ERROR),
    HMAC_GENERATION_FAILED(50004, "HMAC generation failed", "Không thể tạo mã xác thực.", HttpStatus.INTERNAL_SERVER_ERROR),
    SHA256_DIGEST_FAILED(50005, "SHA-256 digest failed", "Không thể tạo mã kiểm tra tệp.", HttpStatus.INTERNAL_SERVER_ERROR),
    SNOWFLAKE_CLOCK_MOVED_BACKWARDS(50006, "Snowflake clock moved backwards", "Hệ thống thời gian không hợp lệ, không thể tạo mã định danh.", HttpStatus.INTERNAL_SERVER_ERROR),
    DUPLICATE_SCHEDULED_TASK_HANDLER(50007, "Duplicate scheduled task handler", "Cấu hình tác vụ định kỳ bị trùng.", HttpStatus.INTERNAL_SERVER_ERROR),
    SCHEDULED_TASK_HANDLER_NOT_FOUND(50008, "Scheduled task handler not found", "Không tìm thấy bộ xử lý cho tác vụ định kỳ.", HttpStatus.INTERNAL_SERVER_ERROR),
    UNSUPPORTED_RECURRING_TASK(50009, "Unsupported recurring task", "Tác vụ không được hỗ trợ lịch chạy định kỳ.", HttpStatus.INTERNAL_SERVER_ERROR),
    UNSUPPORTED_NOTIFICATION_TASK(50010, "Unsupported notification task", "Loại tác vụ thông báo không được hỗ trợ.", HttpStatus.INTERNAL_SERVER_ERROR),
    ;
    int code;
    String message;
    String details;
    HttpStatusCode statusCode;
}
