package com.sep490.hdbhms.occupancy.domain.valueObjects;

public enum ContractEventType {
    CREATED, SIGNED, RENEWED, NOTICE_SENT, INTENTION_RECORDED, EXPIRED, LIQUIDATED, AUTO_TERMINATED, PRICE_CHANGED, OCCUPANT_CHANGED, TRANSFERRED, RENEWAL_AFTER_MOVE_OUT_INTENT
}
