package com.sep490.hdbhms.occupancy.domain.value_objects;

public enum ContractEventType {
    CREATED,
    SIGNED,
    RENEWED,
    NOTICE_SENT,
    INTENTION_RECORDED,
    EXPIRED,
    LIQUIDATED,
    AUTO_TERMINATED,
    PRICE_CHANGED,
    PAYMENT_CYCLE_CHANGED,
    OCCUPANT_CHANGED,
    TRANSFERRED,
    RENEWAL_AFTER_MOVE_OUT_INTENT,
    LIQUIDATION_PROCESSING_STARTED
}
