package com.sep490.hdbhms.occupancy.domain.value_objects;

public enum TransferRequestStatus {
    REQUESTED,
    CANCELLED,
    REJECTED,
    WAITING_MANAGER_APPROVAL,
    MANAGER_APPROVED,
    WAITING_HOLDER_RESPONSE,
    WAITING_TARGET_HOLDER_APPROVAL,
    WAITING_TENANT_CONFIRMATION,
    WAITING_NEW_CONTRACT,
    WAITING_CONTRACT_CONFIRMATION,
    WAITING_SIGNING,
    WAITING_CONTRACT_SIGNING,
    WAITING_PAYMENT,
    WAITING_TRANSFER_DATE,
    WAITING_EXECUTION,
    READY_FOR_HANDOVER,
    EXECUTED,
    COMPLETED,
    EXPIRED
}
