ALTER TABLE invoices
    DROP COLUMN currency,
    MODIFY COLUMN subtotal_amount  BIGINT UNSIGNED NOT NULL DEFAULT 0,
    MODIFY COLUMN discount_amount  BIGINT UNSIGNED NOT NULL DEFAULT 0,
    MODIFY COLUMN total_amount     BIGINT UNSIGNED NOT NULL DEFAULT 0,
    MODIFY COLUMN paid_amount      BIGINT UNSIGNED NOT NULL DEFAULT 0,
    MODIFY COLUMN remaining_amount BIGINT UNSIGNED NOT NULL DEFAULT 0;