CREATE TABLE pending_billing_charges
(
    id                 BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    property_id        BIGINT UNSIGNED                                                                                                      NOT NULL,
    room_id            BIGINT UNSIGNED                                                                                                      NULL,
    contract_id        BIGINT UNSIGNED                                                                                                      NULL,
    source_type        VARCHAR(100)                                                                                                         NOT NULL,
    source_id          BIGINT UNSIGNED                                                                                                      NOT NULL,
    line_type          ENUM ('ROOM_RENT','ELECTRICITY','WATER','SERVICE_FEE','MAINTENANCE_COMPENSATION','VIOLATION_FINE','TRANSFER_DIFFERENCE','DEPOSIT_DEDUCTION','MANUAL_ADJUSTMENT','OTHER') NOT NULL,
    description        VARCHAR(1000)                                                                                                        NOT NULL,
    amount             BIGINT UNSIGNED                                                                                                      NOT NULL,
    billing_period     CHAR(7)                                                                                                              NOT NULL,
    scheduled_issue_at DATETIME(6)                                                                                                          NOT NULL,
    due_date           DATETIME(6)                                                                                                          NOT NULL,
    status             ENUM ('SCHEDULED','BILLED','CANCELLED','FAILED')                                                                     NOT NULL DEFAULT 'SCHEDULED',
    invoice_id         BIGINT UNSIGNED                                                                                                      NULL,
    failure_reason     VARCHAR(1000)                                                                                                        NULL,
    created_by         BIGINT UNSIGNED                                                                                                      NULL,
    created_at         DATETIME(6)                                                                                                          NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at         DATETIME(6)                                                                                                          NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    KEY idx_pending_billing_due (status, scheduled_issue_at),
    KEY idx_pending_billing_source (source_type, source_id, status),
    KEY idx_pending_billing_contract_period (contract_id, billing_period, status),
    CONSTRAINT fk_pbc_property FOREIGN KEY (property_id) REFERENCES properties (id),
    CONSTRAINT fk_pbc_room FOREIGN KEY (room_id) REFERENCES rooms (id),
    CONSTRAINT fk_pbc_contract FOREIGN KEY (contract_id) REFERENCES lease_contracts (id),
    CONSTRAINT fk_pbc_invoice FOREIGN KEY (invoice_id) REFERENCES invoices (id),
    CONSTRAINT fk_pbc_user FOREIGN KEY (created_by) REFERENCES users (id)
) ENGINE = InnoDB;
